/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author muham
 */
public class AdminPanel extends javax.swing.JFrame {

    private Color klik, utama;

    public AdminPanel() {
        initComponents();

        klik = Color.BLUE;
        utama = new Color(250, 128, 114);

        jTable1.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        jTable1.getTableHeader().setOpaque(false);
        jTable1.getTableHeader().setBackground(Color.GREEN);
        jTable1.getTableHeader().setForeground(Color.ORANGE);
        jTable1.setRowHeight(25);

        jTable2.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        jTable2.getTableHeader().setOpaque(false);
        jTable2.getTableHeader().setBackground(Color.GREEN);
        jTable2.getTableHeader().setForeground(Color.ORANGE);
        jTable2.setRowHeight(25);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuPanel = new javax.swing.JPanel();
        tvData = new javax.swing.JLabel();
        imgLogo = new javax.swing.JLabel();
        tvCashier = new javax.swing.JLabel();
        tvMember = new javax.swing.JLabel();
        tvUser = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        WelcomePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        imgWelcome = new javax.swing.JLabel();
        DataPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        MainPanelAdmin = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        CashierPanel = new javax.swing.JPanel();
        tfUsernameKasir = new javax.swing.JTextField();
        tpPasswordKaisr = new javax.swing.JTextField();
        tfNamaKasir = new javax.swing.JTextField();
        tfNoTelpKasir = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        taAlamatKasir = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        btnBaruKasir = new javax.swing.JButton();
        btnSimpanKasir = new javax.swing.JButton();
        btnUbahKasir = new javax.swing.JButton();
        btnHapusKasir = new javax.swing.JButton();
        btnBatalKasir = new javax.swing.JButton();
        jcJenisKleaminKaisr = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        MemberPanel = new javax.swing.JPanel();
        tfNoTelponMmber = new javax.swing.JTextField();
        tfMemberId = new javax.swing.JTextField();
        tfNamaMember = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        taaAlamatMember = new javax.swing.JTextArea();
        jcJenisKelaminMember = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        btnBaruMember = new javax.swing.JButton();
        btnSimpanMember = new javax.swing.JButton();
        btnUbahMember = new javax.swing.JButton();
        btnHapusMember = new javax.swing.JButton();
        btnBatalMember = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ProfilePanel = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuPanel.setBackground(new java.awt.Color(255, 255, 255));
        MenuPanel.setForeground(new java.awt.Color(255, 255, 255));
        MenuPanel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        tvData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tvData.setForeground(new java.awt.Color(250, 128, 114));
        tvData.setText("Data");
        tvData.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tvData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tvDataMouseClicked(evt);
            }
        });

        imgLogo.setForeground(new java.awt.Color(250, 128, 114));
        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/logo.png"))); // NOI18N
        imgLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgLogoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imgLogoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imgLogoMouseExited(evt);
            }
        });

        tvCashier.setForeground(new java.awt.Color(250, 128, 114));
        tvCashier.setText("Cashier");
        tvCashier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tvCashier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tvCashierMouseClicked(evt);
            }
        });

        tvMember.setForeground(new java.awt.Color(250, 128, 114));
        tvMember.setText("Member");
        tvMember.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tvMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tvMemberMouseClicked(evt);
            }
        });

        tvUser.setForeground(new java.awt.Color(250, 128, 114));
        tvUser.setText("Hi, User");
        tvUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tvUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tvUserMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgLogo)
                .addGap(341, 341, 341)
                .addComponent(tvData)
                .addGap(68, 68, 68)
                .addComponent(tvCashier)
                .addGap(51, 51, 51)
                .addComponent(tvMember)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 327, Short.MAX_VALUE)
                .addComponent(tvUser)
                .addGap(96, 96, 96))
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuPanelLayout.createSequentialGroup()
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tvData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tvCashier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tvMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tvUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuPanelLayout.createSequentialGroup()
                .addGap(0, 5, Short.MAX_VALUE)
                .addComponent(imgLogo))
        );

        getContentPane().add(MenuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 60));

        MainPanel.setBackground(new java.awt.Color(102, 102, 0));
        MainPanel.setLayout(new java.awt.CardLayout());

        WelcomePanel.setBackground(new java.awt.Color(153, 153, 255));
        WelcomePanel.setLayout(null);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("jLabel2");
        WelcomePanel.add(jLabel2);
        jLabel2.setBounds(40, 300, 150, 30);

        imgWelcome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/WelcomeAdmin.png"))); // NOI18N
        imgWelcome.setText("jLabel1");
        WelcomePanel.add(imgWelcome);
        imgWelcome.setBounds(0, 0, 1150, 650);

        MainPanel.add(WelcomePanel, "card2");

        DataPanel.setBackground(new java.awt.Color(0, 102, 153));
        DataPanel.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Item 2");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        DataPanel.add(jLabel7);
        jLabel7.setBounds(870, 50, 90, 17);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Data Transaksi");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        DataPanel.add(jLabel6);
        jLabel6.setBounds(200, 50, 120, 17);

        MainPanelAdmin.setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 51, 0));
        jPanel1.setOpaque(false);

        jScrollPane1.setFocusable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setFocusable(false);
        jTable1.setOpaque(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );

        MainPanelAdmin.add(jPanel1, "card2");

        jPanel2.setBackground(new java.awt.Color(204, 204, 0));
        jPanel2.setOpaque(false);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Ginok", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        MainPanelAdmin.add(jPanel2, "card3");

        DataPanel.add(MainPanelAdmin);
        MainPanelAdmin.setBounds(50, 120, 1040, 390);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/BlankPanel.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        DataPanel.add(jLabel1);
        jLabel1.setBounds(0, 0, 1150, 640);

        MainPanel.add(DataPanel, "card3");

        CashierPanel.setBackground(new java.awt.Color(51, 102, 255));
        CashierPanel.setLayout(null);

        tfUsernameKasir.setBorder(null);
        CashierPanel.add(tfUsernameKasir);
        tfUsernameKasir.setBounds(300, 100, 240, 30);

        tpPasswordKaisr.setBorder(null);
        CashierPanel.add(tpPasswordKaisr);
        tpPasswordKaisr.setBounds(300, 160, 230, 30);

        tfNamaKasir.setBorder(null);
        tfNamaKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaKasirActionPerformed(evt);
            }
        });
        CashierPanel.add(tfNamaKasir);
        tfNamaKasir.setBounds(300, 220, 230, 30);

        tfNoTelpKasir.setBorder(null);
        CashierPanel.add(tfNoTelpKasir);
        tfNoTelpKasir.setBounds(310, 500, 220, 30);

        taAlamatKasir.setColumns(20);
        taAlamatKasir.setRows(5);
        taAlamatKasir.setBorder(null);
        taAlamatKasir.setCaretColor(new java.awt.Color(153, 153, 153));
        taAlamatKasir.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        taAlamatKasir.setOpaque(false);
        taAlamatKasir.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        taAlamatKasir.setSelectionColor(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(taAlamatKasir);

        CashierPanel.add(jScrollPane3);
        jScrollPane3.setBounds(310, 336, 200, 140);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable5MouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(jTable5);

        CashierPanel.add(jScrollPane7);
        jScrollPane7.setBounds(580, 90, 530, 370);

        btnBaruKasir.setText("Baru");
        btnBaruKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaruKasirActionPerformed(evt);
            }
        });
        CashierPanel.add(btnBaruKasir);
        btnBaruKasir.setBounds(590, 480, 90, 40);

        btnSimpanKasir.setText("Simpan");
        btnSimpanKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanKasirActionPerformed(evt);
            }
        });
        CashierPanel.add(btnSimpanKasir);
        btnSimpanKasir.setBounds(700, 480, 90, 40);

        btnUbahKasir.setText("Ubah");
        btnUbahKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahKasirActionPerformed(evt);
            }
        });
        CashierPanel.add(btnUbahKasir);
        btnUbahKasir.setBounds(810, 480, 80, 40);

        btnHapusKasir.setText("Hapus");
        btnHapusKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusKasirActionPerformed(evt);
            }
        });
        CashierPanel.add(btnHapusKasir);
        btnHapusKasir.setBounds(920, 480, 80, 40);

        btnBatalKasir.setText("Batal");
        btnBatalKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalKasirActionPerformed(evt);
            }
        });
        CashierPanel.add(btnBatalKasir);
        btnBatalKasir.setBounds(1030, 480, 80, 40);

        jcJenisKleaminKaisr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gender", "Laki - Laki", "Perempuan", " " }));
        CashierPanel.add(jcJenisKleaminKaisr);
        jcJenisKleaminKaisr.setBounds(300, 280, 210, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Profile.png"))); // NOI18N
        CashierPanel.add(jLabel5);
        jLabel5.setBounds(0, 0, 1155, 651);

        jTextField1.setText("jTextField1");
        CashierPanel.add(jTextField1);
        jTextField1.setBounds(310, 220, 220, 30);

        MainPanel.add(CashierPanel, "card4");

        MemberPanel.setBackground(new java.awt.Color(51, 51, 51));
        MemberPanel.setLayout(null);

        tfNoTelponMmber.setBorder(null);
        tfNoTelponMmber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNoTelponMmberKeyTyped(evt);
            }
        });
        MemberPanel.add(tfNoTelponMmber);
        tfNoTelponMmber.setBounds(290, 460, 220, 30);

        tfMemberId.setBorder(null);
        tfMemberId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMemberIdActionPerformed(evt);
            }
        });
        tfMemberId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfMemberIdKeyTyped(evt);
            }
        });
        MemberPanel.add(tfMemberId);
        tfMemberId.setBounds(290, 110, 220, 40);

        tfNamaMember.setBorder(null);
        tfNamaMember.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNamaMemberKeyTyped(evt);
            }
        });
        MemberPanel.add(tfNamaMember);
        tfNamaMember.setBounds(290, 170, 220, 30);

        taaAlamatMember.setColumns(20);
        taaAlamatMember.setRows(5);
        jScrollPane4.setViewportView(taaAlamatMember);

        MemberPanel.add(jScrollPane4);
        jScrollPane4.setBounds(290, 286, 210, 140);

        jcJenisKelaminMember.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gender", "Laki - Laki", "Perempuan" }));
        MemberPanel.add(jcJenisKelaminMember);
        jcJenisKelaminMember.setBounds(290, 230, 220, 30);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTable3);

        MemberPanel.add(jScrollPane5);
        jScrollPane5.setBounds(600, 100, 510, 340);

        btnBaruMember.setText("Baru");
        btnBaruMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaruMemberActionPerformed(evt);
            }
        });
        MemberPanel.add(btnBaruMember);
        btnBaruMember.setBounds(590, 460, 90, 40);

        btnSimpanMember.setText("Simpan");
        btnSimpanMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanMemberActionPerformed(evt);
            }
        });
        MemberPanel.add(btnSimpanMember);
        btnSimpanMember.setBounds(700, 460, 80, 40);

        btnUbahMember.setText("Ubah");
        btnUbahMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahMemberActionPerformed(evt);
            }
        });
        MemberPanel.add(btnUbahMember);
        btnUbahMember.setBounds(800, 460, 90, 40);

        btnHapusMember.setText("Hapus");
        btnHapusMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusMemberActionPerformed(evt);
            }
        });
        MemberPanel.add(btnHapusMember);
        btnHapusMember.setBounds(920, 460, 80, 40);

        btnBatalMember.setText("Batal");
        btnBatalMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalMemberActionPerformed(evt);
            }
        });
        MemberPanel.add(btnBatalMember);
        btnBatalMember.setBounds(1020, 460, 80, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/MemberPanel.png"))); // NOI18N
        MemberPanel.add(jLabel4);
        jLabel4.setBounds(0, 0, 1155, 651);

        MainPanel.add(MemberPanel, "card5");

        ProfilePanel.setLayout(null);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable4);

        ProfilePanel.add(jScrollPane6);
        jScrollPane6.setBounds(610, 100, 490, 350);

        jButton1.setText("Baru");
        ProfilePanel.add(jButton1);
        jButton1.setBounds(600, 470, 80, 40);

        jButton2.setText("Simpan");
        ProfilePanel.add(jButton2);
        jButton2.setBounds(700, 470, 90, 40);

        jButton3.setText("Ubah");
        ProfilePanel.add(jButton3);
        jButton3.setBounds(810, 470, 90, 40);

        jButton4.setText("Hapus");
        ProfilePanel.add(jButton4);
        jButton4.setBounds(920, 470, 80, 40);

        jButton5.setText("Batal");
        ProfilePanel.add(jButton5);
        jButton5.setBounds(1023, 470, 80, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Profile.png"))); // NOI18N
        ProfilePanel.add(jLabel3);
        jLabel3.setBounds(0, 0, 1150, 650);

        MainPanel.add(ProfilePanel, "card6");

        getContentPane().add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1150, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        dispose();
        Login.summonLoginPanel();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        jLabel1.setText("Hi, " + Encapsulation.getName());
        MainPanelAdmin.removeAll();
        MainPanelAdmin.repaint();
        MainPanelAdmin.revalidate();

        MainPanelAdmin.add(jPanel2);
        MainPanelAdmin.repaint();
        MainPanelAdmin.revalidate();

        jLabel6.setForeground(utama);
        jLabel7.setForeground(klik);

        EnableMember(1);
        EnableKasir(1);
    }//GEN-LAST:event_formWindowOpened

    private void tvUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tvUserMouseClicked
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();

        MainPanel.add(ProfilePanel);
        MainPanel.repaint();
        MainPanel.revalidate();

        imgLogo.setForeground(utama);
        tvData.setForeground(utama);

        tvCashier.setForeground(utama);
        tvMember.setForeground(utama);
        tvUser.setForeground(klik);
    }//GEN-LAST:event_tvUserMouseClicked

    private void tvMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tvMemberMouseClicked
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();

        MainPanel.add(MemberPanel);
        MainPanel.repaint();
        MainPanel.revalidate();

        tvMember.setForeground(klik);
        imgLogo.setForeground(utama);
        tvData.setForeground(utama);
        tvCashier.setForeground(utama);
        tvUser.setForeground(utama);

    }//GEN-LAST:event_tvMemberMouseClicked

    private void tvCashierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tvCashierMouseClicked
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();

        MainPanel.add(CashierPanel);
        MainPanel.repaint();
        MainPanel.revalidate();

        imgLogo.setForeground(utama);
        tvData.setForeground(utama);

        tvCashier.setForeground(klik);
        tvMember.setForeground(utama);
        tvUser.setForeground(utama);
    }//GEN-LAST:event_tvCashierMouseClicked

    private void imgLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgLogoMouseClicked
        AboutPanel.summonAboutPanel();
    }//GEN-LAST:event_imgLogoMouseClicked

    private void tvDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tvDataMouseClicked
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();

        MainPanel.add(DataPanel);
        MainPanel.repaint();
        MainPanel.revalidate();

        tvData.setForeground(klik);
        imgLogo.setForeground(utama);
        tvCashier.setForeground(utama);
        tvMember.setForeground(utama);
        tvUser.setForeground(utama);

    }//GEN-LAST:event_tvDataMouseClicked

    private void imgLogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgLogoMouseEntered
        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/logoGlow.png")));
    }//GEN-LAST:event_imgLogoMouseEntered

    private void imgLogoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgLogoMouseExited
        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/logo.png")));
    }//GEN-LAST:event_imgLogoMouseExited

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        MainPanelAdmin.removeAll();
        MainPanelAdmin.repaint();
        MainPanelAdmin.revalidate();

        MainPanelAdmin.add(jPanel2);
        MainPanelAdmin.repaint();
        MainPanelAdmin.revalidate();

        jLabel6.setForeground(utama);
        jLabel7.setForeground(klik);

    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        MainPanelAdmin.removeAll();
        MainPanelAdmin.repaint();
        MainPanelAdmin.revalidate();

        MainPanelAdmin.add(jPanel1);
        MainPanelAdmin.repaint();
        MainPanelAdmin.revalidate();

        jLabel6.setForeground(klik);
        jLabel7.setForeground(utama);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void tfMemberIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMemberIdKeyTyped
        if (tfMemberId.getText().length() == 5) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Product Id Melebihi 5 karakter", "Informasi", JOptionPane.WARNING_MESSAGE);

        }

        char angka = evt.getKeyChar();

        if (!(Character.isDigit(angka) || angka == KeyEvent.VK_BACK_SPACE || angka == KeyEvent.VK_DELETE)) {

            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(this, "Inputan Harus Berbentuk Angka", "Informasi", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_tfMemberIdKeyTyped

    private void tfNamaMemberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNamaMemberKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaMemberKeyTyped

    private void tfMemberIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMemberIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMemberIdActionPerformed

    private void tfNoTelponMmberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNoTelponMmberKeyTyped
        if (tfNoTelponMmber.getText().length() == 13) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Product Id Melebihi 13 karakter", "Informasi", JOptionPane.WARNING_MESSAGE);

        }

        char angka = evt.getKeyChar();

        if (!(Character.isDigit(angka) || angka == KeyEvent.VK_BACK_SPACE || angka == KeyEvent.VK_DELETE || angka == KeyEvent.VK_ENTER)) {

            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(this, "Inputan Harus Berbentuk Angka", "Informasi", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_tfNoTelponMmberKeyTyped

    private void btnBaruMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaruMemberActionPerformed
        EnableMember(2);
    }//GEN-LAST:event_btnBaruMemberActionPerformed

    private void btnSimpanMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanMemberActionPerformed
        EnableMember(3);

    }//GEN-LAST:event_btnSimpanMemberActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        EnableMember(4);
    }//GEN-LAST:event_jTable3MouseClicked

    private void btnUbahMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahMemberActionPerformed
        EnableMember(5);
    }//GEN-LAST:event_btnUbahMemberActionPerformed

    private void btnHapusMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusMemberActionPerformed
        EnableMember(6);
    }//GEN-LAST:event_btnHapusMemberActionPerformed

    private void btnBatalMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalMemberActionPerformed
        EnableMember(7);
    }//GEN-LAST:event_btnBatalMemberActionPerformed

    private void tfNamaKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaKasirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaKasirActionPerformed

    private void btnBaruKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaruKasirActionPerformed
        EnableKasir(2);
    }//GEN-LAST:event_btnBaruKasirActionPerformed

    private void btnSimpanKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanKasirActionPerformed
        EnableKasir(3);
    }//GEN-LAST:event_btnSimpanKasirActionPerformed

    private void jTable5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable5MouseClicked
        EnableKasir(4);
    }//GEN-LAST:event_jTable5MouseClicked

    private void btnUbahKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahKasirActionPerformed
        EnableKasir(5);
    }//GEN-LAST:event_btnUbahKasirActionPerformed

    private void btnHapusKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusKasirActionPerformed
        EnableKasir(6);
    }//GEN-LAST:event_btnHapusKasirActionPerformed

    private void btnBatalKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalKasirActionPerformed
        EnableKasir(7);
    }//GEN-LAST:event_btnBatalKasirActionPerformed

    private void EnableKasir(int mode) {
        if (mode == 1) {
            //windows opened
            tfUsernameKasir.setEnabled(false);
            tfNamaKasir.setEnabled(false);
            tpPasswordKaisr.setEnabled(false);
            jcJenisKleaminKaisr.setEnabled(false);
            taAlamatKasir.setEnabled(false);
            tfNoTelpKasir.setEnabled(false);

            btnBaruKasir.setEnabled(true);
            btnSimpanKasir.setEnabled(false);
            btnUbahKasir.setEnabled(false);
            btnHapusKasir.setEnabled(false);
            btnBatalKasir.setEnabled(false);
            btnBaruKasir.requestFocus();

        } else if (mode == 2) {
            //btnBaru
            tfUsernameKasir.setEnabled(true);
            tfNamaKasir.setEnabled(true);
            tpPasswordKaisr.setEnabled(true);
            jcJenisKleaminKaisr.setEnabled(true);
            taAlamatKasir.setEnabled(true);
            tfNoTelpKasir.setEnabled(true);

            btnBaruKasir.setEnabled(false);
            btnSimpanKasir.setEnabled(true);
            btnUbahKasir.setEnabled(false);
            btnHapusKasir.setEnabled(false);
            btnBatalKasir.setEnabled(false);
            btnSimpanKasir.requestFocus();
            tfUsernameKasir.requestFocus();

        } else if (mode == 3) {

            //btnsimpan
            tfUsernameKasir.setEnabled(false);
            tfNamaKasir.setEnabled(false);
            tpPasswordKaisr.setEnabled(false);
            jcJenisKleaminKaisr.setEnabled(false);
            taAlamatKasir.setEnabled(false);
            tfNoTelpKasir.setEnabled(false);

            btnBaruKasir.setEnabled(true);
            btnSimpanKasir.setEnabled(false);
            btnUbahKasir.setEnabled(false);
            btnHapusKasir.setEnabled(false);
            btnBatalKasir.setEnabled(true);
            btnBaruKasir.requestFocus();

        } else if (mode == 4) {

            //klik tabel
            tfUsernameKasir.setEnabled(false);
            tfNamaKasir.setEnabled(false);
            tpPasswordKaisr.setEnabled(false);
            jcJenisKleaminKaisr.setEnabled(false);
            taAlamatKasir.setEnabled(false);
            tfNoTelpKasir.setEnabled(false);

            btnBaruKasir.setEnabled(false);
            btnSimpanKasir.setEnabled(false);
            btnUbahKasir.setEnabled(true);
            btnHapusKasir.setEnabled(true);
            btnBatalKasir.setEnabled(true);
            btnUbahKasir.requestFocus();

        } else if (mode == 5) {
            //ubah
            tfUsernameKasir.setEnabled(true);
            tfNamaKasir.setEnabled(true);
            tpPasswordKaisr.setEnabled(true);
            jcJenisKleaminKaisr.setEnabled(true);
            taAlamatKasir.setEnabled(true);
            tfNoTelpKasir.setEnabled(true);

            btnBaruKasir.setEnabled(false);
            btnSimpanKasir.setEnabled(true);
            btnUbahKasir.setEnabled(false);
            btnHapusKasir.setEnabled(false);
            btnBatalKasir.setEnabled(true);
            btnSimpanKasir.requestFocus();
            tfUsernameKasir.requestFocus();

        } else if (mode == 6) {
            //hapus
            tfUsernameKasir.setEnabled(false);
            tfNamaKasir.setEnabled(false);
            tpPasswordKaisr.setEnabled(false);
            jcJenisKleaminKaisr.setEnabled(false);
            taAlamatKasir.setEnabled(false);
            tfNoTelpKasir.setEnabled(false);

            btnBaruKasir.setEnabled(true);
            btnSimpanKasir.setEnabled(false);
            btnUbahKasir.setEnabled(false);
            btnHapusKasir.setEnabled(false);
            btnBatalKasir.setEnabled(false);
            btnBatalKasir.requestFocus();

        } else if (mode == 7) {

            //batal
            tfUsernameKasir.setEnabled(true);
            tfNamaKasir.setEnabled(true);
            tpPasswordKaisr.setEnabled(true);
            jcJenisKleaminKaisr.setEnabled(true);
            taAlamatKasir.setEnabled(true);
            tfNoTelpKasir.setEnabled(true);

            btnBaruKasir.setEnabled(false);
            btnSimpanKasir.setEnabled(true);
            btnUbahKasir.setEnabled(false);
            btnHapusKasir.setEnabled(false);
            btnBatalKasir.setEnabled(true);
            btnSimpanKasir.requestFocus();
            tfUsernameKasir.requestFocus();

        }

    }

    private void EnableMember(int mode) {
        if (mode == 1) {

            //windows opened
            tfMemberId.setEnabled(false);
            tfNamaMember.setEnabled(false);
            jcJenisKelaminMember.setEnabled(false);
            taaAlamatMember.setEnabled(false);
            tfNoTelponMmber.setEnabled(false);

            btnBaruMember.setEnabled(true);
            btnSimpanMember.setEnabled(false);
            btnUbahMember.setEnabled(false);
            btnHapusMember.setEnabled(false);
            btnBatalMember.setEnabled(false);

            btnBaruMember.requestFocus();

        } else if (mode == 2) {

            //btn baru ketika di klik 
            tfMemberId.setEnabled(true);
            tfNamaMember.setEnabled(true);
            jcJenisKelaminMember.setEnabled(true);
            taaAlamatMember.setEnabled(true);
            tfNoTelponMmber.setEnabled(true);

            btnBaruMember.setEnabled(false);
            btnSimpanMember.setEnabled(true);
            btnUbahMember.setEnabled(false);
            btnHapusMember.setEnabled(false);
            btnBatalMember.setEnabled(false);
            btnSimpanMember.requestFocus();
            tfMemberId.requestFocus();

        } else if (mode == 3) {
            //btn simpan ketika di klik 
            tfMemberId.setEnabled(false);
            tfNamaMember.setEnabled(false);
            jcJenisKelaminMember.setEnabled(false);
            taaAlamatMember.setEnabled(false);
            tfNoTelponMmber.setEnabled(false);

            btnBaruMember.setEnabled(true);
            btnSimpanMember.setEnabled(false);
            btnUbahMember.setEnabled(false);
            btnHapusMember.setEnabled(false);
            btnBatalMember.setEnabled(true);
            btnBaruMember.requestFocus();

        } else if (mode == 4) {
            //klik di tabel
            tfMemberId.setEnabled(false);
            tfNamaMember.setEnabled(true);
            jcJenisKelaminMember.setEnabled(true);
            taaAlamatMember.setEnabled(true);
            tfNoTelponMmber.setEnabled(true);

            btnBaruMember.setEnabled(false);
            btnSimpanMember.setEnabled(false);
            btnUbahMember.setEnabled(true);
            btnHapusMember.setEnabled(true);
            btnBatalMember.setEnabled(true);
            btnUbahMember.requestFocus();

        } else if (mode == 5) {

            //ubah
            tfMemberId.setEnabled(true);
            tfNamaMember.setEnabled(true);
            jcJenisKelaminMember.setEnabled(true);
            taaAlamatMember.setEnabled(true);
            tfNoTelponMmber.setEnabled(true);

            btnBaruMember.setEnabled(false);
            btnSimpanMember.setEnabled(true);
            btnUbahMember.setEnabled(false);
            btnHapusMember.setEnabled(false);
            btnBatalMember.setEnabled(true);
            btnSimpanMember.requestFocus();
            tfMemberId.requestFocus();

        } else if (mode == 6) {
            //hapus
            tfMemberId.setEnabled(false);
            tfNamaMember.setEnabled(false);
            jcJenisKelaminMember.setEnabled(false);
            taaAlamatMember.setEnabled(false);
            tfNoTelponMmber.setEnabled(false);

            btnBaruMember.setEnabled(true);
            btnSimpanMember.setEnabled(false);
            btnUbahMember.setEnabled(false);
            btnHapusMember.setEnabled(false);
            btnBatalMember.setEnabled(false);
            btnBaruMember.requestFocus();

        } else if (mode == 7) {

            //batal
            tfMemberId.setEnabled(true);
            tfNamaMember.setEnabled(true);
            jcJenisKelaminMember.setEnabled(true);
            taaAlamatMember.setEnabled(true);
            tfNoTelponMmber.setEnabled(true);

            btnBaruMember.setEnabled(false);
            btnSimpanMember.setEnabled(true);
            btnUbahMember.setEnabled(false);
            btnHapusMember.setEnabled(false);
            btnBatalMember.setEnabled(true);
            btnSimpanMember.requestFocus();
            tfMemberId.requestFocus();

        }
    }

    public static void summonAdminPanel() {
        AdminPanel adminPanel = new AdminPanel();
        adminPanel.setSize(1150, 695);
        adminPanel.setLocationRelativeTo(null);
        adminPanel.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                summonAdminPanel();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CashierPanel;
    private javax.swing.JPanel DataPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel MainPanelAdmin;
    private javax.swing.JPanel MemberPanel;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JPanel ProfilePanel;
    private javax.swing.JPanel WelcomePanel;
    private javax.swing.JButton btnBaruKasir;
    private javax.swing.JButton btnBaruMember;
    private javax.swing.JButton btnBatalKasir;
    private javax.swing.JButton btnBatalMember;
    private javax.swing.JButton btnHapusKasir;
    private javax.swing.JButton btnHapusMember;
    private javax.swing.JButton btnSimpanKasir;
    private javax.swing.JButton btnSimpanMember;
    private javax.swing.JButton btnUbahKasir;
    private javax.swing.JButton btnUbahMember;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel imgWelcome;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> jcJenisKelaminMember;
    private javax.swing.JComboBox<String> jcJenisKleaminKaisr;
    private javax.swing.JTextArea taAlamatKasir;
    private javax.swing.JTextArea taaAlamatMember;
    private javax.swing.JTextField tfMemberId;
    private javax.swing.JTextField tfNamaKasir;
    private javax.swing.JTextField tfNamaMember;
    private javax.swing.JTextField tfNoTelpKasir;
    private javax.swing.JTextField tfNoTelponMmber;
    private javax.swing.JTextField tfUsernameKasir;
    private javax.swing.JTextField tpPasswordKaisr;
    private javax.swing.JLabel tvCashier;
    private javax.swing.JLabel tvData;
    private javax.swing.JLabel tvMember;
    private javax.swing.JLabel tvUser;
    // End of variables declaration//GEN-END:variables
}
