/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author muham
 */
public class AdminPanel extends javax.swing.JFrame {

    private Color klik, utama;
    private ResultSet hasil;
    private Boolean saveMode;
    private DefaultTableModel memberTable, cashierTable, dataTransactionTable, dataProductTable;

    public AdminPanel() {
        initComponents();

        klik = Color.BLUE;
        utama = new Color(250, 128, 114);
        desainTabel();

        // koneksi table
        memberTable = (DefaultTableModel) MemberTable.getModel();
        cashierTable = (DefaultTableModel) CashierTable.getModel();
        dataProductTable = (DefaultTableModel) DataProductTable.getModel();
        dataTransactionTable = (DefaultTableModel) DataTransactionTable.getModel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuPanel = new javax.swing.JPanel();
        tvData = new javax.swing.JLabel();
        imgLogo = new javax.swing.JLabel();
        tvCashier = new javax.swing.JLabel();
        tvMember = new javax.swing.JLabel();
        tvUser = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        WelcomePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        imgWelcome = new javax.swing.JLabel();
        DataPanel = new javax.swing.JPanel();
        tvDataProduct = new javax.swing.JLabel();
        tvDataTransaction = new javax.swing.JLabel();
        MainPanelAdmin = new javax.swing.JPanel();
        ProductTablePanel = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        DataProductTable = new javax.swing.JTable();
        TransactionTablePanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DataTransactionTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        CashierPanel = new javax.swing.JPanel();
        tfUsernameKasir = new javax.swing.JTextField();
        jpPasswordKasir = new javax.swing.JTextField();
        tfNamaKasir = new javax.swing.JTextField();
        tfNoTelpKasir = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        taAlamatKasir = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        CashierTable = new javax.swing.JTable();
        btnBaruKasir = new javax.swing.JButton();
        btnSimpanKasir = new javax.swing.JButton();
        btnUbahKasir = new javax.swing.JButton();
        btnHapusKasir = new javax.swing.JButton();
        btnBatalKasir = new javax.swing.JButton();
        jcJenisKleaminKaisr = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        MemberPanel = new javax.swing.JPanel();
        tfNoTelponMmber = new javax.swing.JTextField();
        tfMemberId = new javax.swing.JTextField();
        tfNamaMember = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        taaAlamatMember = new javax.swing.JTextArea();
        jcJenisKelaminMember = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        MemberTable = new javax.swing.JTable();
        btnBaruMember = new javax.swing.JButton();
        btnSimpanMember = new javax.swing.JButton();
        btnUbahMember = new javax.swing.JButton();
        btnHapusMember = new javax.swing.JButton();
        btnBatalMember = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        ProfilePanel = new javax.swing.JPanel();
        btnSimpanProfile = new javax.swing.JButton();
        btnUbahProfile = new javax.swing.JButton();
        btnHapusProfile = new javax.swing.JButton();
        tfUsernameProfile = new javax.swing.JTextField();
        tfNamaProfile = new javax.swing.JTextField();
        jcJenisKelamin = new javax.swing.JComboBox<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        jtaAlamatProfile = new javax.swing.JTextArea();
        tfNoTelpProfile = new javax.swing.JTextField();
        jpPasswordProfile = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuPanel.setBackground(new java.awt.Color(255, 255, 255));
        MenuPanel.setForeground(new java.awt.Color(255, 255, 255));
        MenuPanel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        tvData.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tvData.setForeground(new java.awt.Color(250, 128, 114));
        tvData.setText("Data");
        tvData.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tvData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tvDataMouseClicked(evt);
            }
        });

        imgLogo.setForeground(new java.awt.Color(250, 128, 114));
        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/logo.png"))); // NOI18N
        imgLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imgLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgLogoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                imgLogoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                imgLogoMouseExited(evt);
            }
        });

        tvCashier.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tvCashier.setForeground(new java.awt.Color(250, 128, 114));
        tvCashier.setText("Cashier");
        tvCashier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tvCashier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tvCashierMouseClicked(evt);
            }
        });

        tvMember.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tvMember.setForeground(new java.awt.Color(250, 128, 114));
        tvMember.setText("Member");
        tvMember.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tvMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tvMemberMouseClicked(evt);
            }
        });

        tvUser.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tvUser.setForeground(new java.awt.Color(250, 128, 114));
        tvUser.setText("Hi, User");
        tvUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tvUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tvUserMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(250, 128, 114));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Logout");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgLogo)
                .addGap(341, 341, 341)
                .addComponent(tvData)
                .addGap(68, 68, 68)
                .addComponent(tvCashier)
                .addGap(51, 51, 51)
                .addComponent(tvMember)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, Short.MAX_VALUE)
                .addComponent(tvUser, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuPanelLayout.createSequentialGroup()
                .addGap(0, 5, Short.MAX_VALUE)
                .addComponent(imgLogo))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuPanelLayout.createSequentialGroup()
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tvData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tvCashier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tvMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tvUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(MenuPanelLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(1, 1, 1)))))
                .addContainerGap())
        );

        getContentPane().add(MenuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 60));

        MainPanel.setBackground(new java.awt.Color(102, 102, 0));
        MainPanel.setLayout(new java.awt.CardLayout());

        WelcomePanel.setBackground(new java.awt.Color(153, 153, 255));
        WelcomePanel.setLayout(null);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("jLabel2");
        WelcomePanel.add(jLabel2);
        jLabel2.setBounds(40, 300, 150, 30);

        imgWelcome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/WelcomeAdmin.png"))); // NOI18N
        imgWelcome.setText("jLabel1");
        WelcomePanel.add(imgWelcome);
        imgWelcome.setBounds(0, 0, 1150, 650);

        MainPanel.add(WelcomePanel, "card2");

        DataPanel.setBackground(new java.awt.Color(0, 102, 153));
        DataPanel.setLayout(null);

        tvDataProduct.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tvDataProduct.setText("Data Product");
        tvDataProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tvDataProductMouseClicked(evt);
            }
        });
        DataPanel.add(tvDataProduct);
        tvDataProduct.setBounds(870, 50, 90, 17);

        tvDataTransaction.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tvDataTransaction.setText("Data Transaksi");
        tvDataTransaction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tvDataTransactionMouseClicked(evt);
            }
        });
        DataPanel.add(tvDataTransaction);
        tvDataTransaction.setBounds(200, 50, 120, 17);

        MainPanelAdmin.setLayout(new java.awt.CardLayout());

        ProductTablePanel.setBackground(new java.awt.Color(255, 51, 0));
        ProductTablePanel.setOpaque(false);

        DataProductTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        DataProductTable.setFocusable(false);
        DataProductTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        DataProductTable.setShowVerticalLines(false);
        DataProductTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane9.setViewportView(DataProductTable);

        javax.swing.GroupLayout ProductTablePanelLayout = new javax.swing.GroupLayout(ProductTablePanel);
        ProductTablePanel.setLayout(ProductTablePanelLayout);
        ProductTablePanelLayout.setHorizontalGroup(
            ProductTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
        );
        ProductTablePanelLayout.setVerticalGroup(
            ProductTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProductTablePanelLayout.createSequentialGroup()
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        MainPanelAdmin.add(ProductTablePanel, "card2");

        TransactionTablePanel.setBackground(new java.awt.Color(204, 204, 0));
        TransactionTablePanel.setOpaque(false);

        DataTransactionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Invoice Number", "Cashier", "Member", "Date", "Product", "Jumlah", "Pembayaran"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        DataTransactionTable.setFocusable(false);
        DataTransactionTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        DataTransactionTable.setShowVerticalLines(false);
        DataTransactionTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(DataTransactionTable);

        javax.swing.GroupLayout TransactionTablePanelLayout = new javax.swing.GroupLayout(TransactionTablePanel);
        TransactionTablePanel.setLayout(TransactionTablePanelLayout);
        TransactionTablePanelLayout.setHorizontalGroup(
            TransactionTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1040, Short.MAX_VALUE)
        );
        TransactionTablePanelLayout.setVerticalGroup(
            TransactionTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransactionTablePanelLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        MainPanelAdmin.add(TransactionTablePanel, "card3");

        DataPanel.add(MainPanelAdmin);
        MainPanelAdmin.setBounds(50, 120, 1040, 390);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/BlankPanel.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        DataPanel.add(jLabel1);
        jLabel1.setBounds(0, 0, 1150, 640);

        MainPanel.add(DataPanel, "card3");

        CashierPanel.setBackground(new java.awt.Color(51, 102, 255));
        CashierPanel.setLayout(null);

        tfUsernameKasir.setBorder(null);
        tfUsernameKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsernameKasirActionPerformed(evt);
            }
        });
        CashierPanel.add(tfUsernameKasir);
        tfUsernameKasir.setBounds(300, 100, 240, 30);

        jpPasswordKasir.setBorder(null);
        CashierPanel.add(jpPasswordKasir);
        jpPasswordKasir.setBounds(300, 160, 230, 30);

        tfNamaKasir.setBorder(null);
        tfNamaKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaKasirActionPerformed(evt);
            }
        });
        CashierPanel.add(tfNamaKasir);
        tfNamaKasir.setBounds(300, 220, 230, 30);

        tfNoTelpKasir.setBorder(null);
        tfNoTelpKasir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNoTelpKasirKeyTyped(evt);
            }
        });
        CashierPanel.add(tfNoTelpKasir);
        tfNoTelpKasir.setBounds(310, 500, 220, 30);

        taAlamatKasir.setColumns(20);
        taAlamatKasir.setRows(5);
        taAlamatKasir.setBorder(null);
        taAlamatKasir.setCaretColor(new java.awt.Color(153, 153, 153));
        taAlamatKasir.setDisabledTextColor(new java.awt.Color(102, 102, 102));
        taAlamatKasir.setOpaque(false);
        taAlamatKasir.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        taAlamatKasir.setSelectionColor(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(taAlamatKasir);

        CashierPanel.add(jScrollPane3);
        jScrollPane3.setBounds(310, 336, 200, 140);

        CashierTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Username", "Password", "Nama", "Jens Kelaminj", "Alamat", "No Telpon"
            }
        ));
        CashierTable.setFocusable(false);
        CashierTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        CashierTable.setShowVerticalLines(false);
        CashierTable.getTableHeader().setReorderingAllowed(false);
        CashierTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CashierTableMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(CashierTable);

        CashierPanel.add(jScrollPane7);
        jScrollPane7.setBounds(580, 90, 530, 370);

        btnBaruKasir.setText("Baru");
        btnBaruKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaruKasirActionPerformed(evt);
            }
        });
        CashierPanel.add(btnBaruKasir);
        btnBaruKasir.setBounds(590, 480, 90, 40);

        btnSimpanKasir.setText("Simpan");
        btnSimpanKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanKasirActionPerformed(evt);
            }
        });
        CashierPanel.add(btnSimpanKasir);
        btnSimpanKasir.setBounds(700, 480, 90, 40);

        btnUbahKasir.setText("Ubah");
        btnUbahKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahKasirActionPerformed(evt);
            }
        });
        CashierPanel.add(btnUbahKasir);
        btnUbahKasir.setBounds(810, 480, 80, 40);

        btnHapusKasir.setText("Hapus");
        btnHapusKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusKasirActionPerformed(evt);
            }
        });
        CashierPanel.add(btnHapusKasir);
        btnHapusKasir.setBounds(920, 480, 80, 40);

        btnBatalKasir.setText("Batal");
        btnBatalKasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalKasirActionPerformed(evt);
            }
        });
        CashierPanel.add(btnBatalKasir);
        btnBatalKasir.setBounds(1030, 480, 80, 40);

        jcJenisKleaminKaisr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jenis Kelamin", "Laki - Laki", "Perempuan", " " }));
        jcJenisKleaminKaisr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcJenisKleaminKaisrActionPerformed(evt);
            }
        });
        CashierPanel.add(jcJenisKleaminKaisr);
        jcJenisKleaminKaisr.setBounds(300, 280, 210, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Profile.png"))); // NOI18N
        CashierPanel.add(jLabel5);
        jLabel5.setBounds(0, 0, 1155, 651);

        jTextField1.setText("jTextField1");
        CashierPanel.add(jTextField1);
        jTextField1.setBounds(310, 220, 220, 30);

        MainPanel.add(CashierPanel, "card4");

        MemberPanel.setBackground(new java.awt.Color(51, 51, 51));
        MemberPanel.setLayout(null);

        tfNoTelponMmber.setBorder(null);
        tfNoTelponMmber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNoTelponMmberKeyTyped(evt);
            }
        });
        MemberPanel.add(tfNoTelponMmber);
        tfNoTelponMmber.setBounds(290, 460, 220, 30);

        tfMemberId.setBorder(null);
        tfMemberId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMemberIdActionPerformed(evt);
            }
        });
        tfMemberId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfMemberIdKeyTyped(evt);
            }
        });
        MemberPanel.add(tfMemberId);
        tfMemberId.setBounds(290, 110, 220, 40);

        tfNamaMember.setBorder(null);
        tfNamaMember.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNamaMemberKeyTyped(evt);
            }
        });
        MemberPanel.add(tfNamaMember);
        tfNamaMember.setBounds(290, 170, 220, 30);

        taaAlamatMember.setColumns(20);
        taaAlamatMember.setRows(5);
        jScrollPane4.setViewportView(taaAlamatMember);

        MemberPanel.add(jScrollPane4);
        jScrollPane4.setBounds(290, 286, 210, 140);

        jcJenisKelaminMember.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jenis Kelamin", "Laki - Laki", "Perempuan" }));
        MemberPanel.add(jcJenisKelaminMember);
        jcJenisKelaminMember.setBounds(290, 230, 220, 30);

        MemberTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Number ID", "Nama", "Jenis Kelamin", "Alamat", "No Telpon"
            }
        ));
        MemberTable.setFocusable(false);
        MemberTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        MemberTable.setShowVerticalLines(false);
        MemberTable.getTableHeader().setReorderingAllowed(false);
        MemberTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MemberTableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(MemberTable);

        MemberPanel.add(jScrollPane5);
        jScrollPane5.setBounds(600, 100, 510, 340);

        btnBaruMember.setText("Baru");
        btnBaruMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaruMemberActionPerformed(evt);
            }
        });
        MemberPanel.add(btnBaruMember);
        btnBaruMember.setBounds(590, 460, 90, 40);

        btnSimpanMember.setText("Simpan");
        btnSimpanMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanMemberActionPerformed(evt);
            }
        });
        MemberPanel.add(btnSimpanMember);
        btnSimpanMember.setBounds(700, 460, 90, 40);

        btnUbahMember.setText("Ubah");
        btnUbahMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahMemberActionPerformed(evt);
            }
        });
        MemberPanel.add(btnUbahMember);
        btnUbahMember.setBounds(810, 460, 90, 40);

        btnHapusMember.setText("Hapus");
        btnHapusMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusMemberActionPerformed(evt);
            }
        });
        MemberPanel.add(btnHapusMember);
        btnHapusMember.setBounds(920, 460, 80, 40);

        btnBatalMember.setText("Batal");
        btnBatalMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalMemberActionPerformed(evt);
            }
        });
        MemberPanel.add(btnBatalMember);
        btnBatalMember.setBounds(1020, 460, 90, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/MemberPanel.png"))); // NOI18N
        MemberPanel.add(jLabel4);
        jLabel4.setBounds(0, 0, 1155, 651);

        MainPanel.add(MemberPanel, "card5");

        ProfilePanel.setLayout(null);

        btnSimpanProfile.setText("Simpan");
        btnSimpanProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanProfileActionPerformed(evt);
            }
        });
        ProfilePanel.add(btnSimpanProfile);
        btnSimpanProfile.setBounds(620, 470, 90, 40);

        btnUbahProfile.setText("Ubah");
        btnUbahProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahProfileActionPerformed(evt);
            }
        });
        ProfilePanel.add(btnUbahProfile);
        btnUbahProfile.setBounds(740, 470, 90, 40);

        btnHapusProfile.setText("Hapus");
        btnHapusProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusProfileActionPerformed(evt);
            }
        });
        ProfilePanel.add(btnHapusProfile);
        btnHapusProfile.setBounds(870, 470, 80, 40);

        tfUsernameProfile.setBorder(null);
        ProfilePanel.add(tfUsernameProfile);
        tfUsernameProfile.setBounds(300, 100, 230, 30);

        tfNamaProfile.setBorder(null);
        ProfilePanel.add(tfNamaProfile);
        tfNamaProfile.setBounds(300, 220, 230, 30);

        jcJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jenis Kelamin", "Laki - Laki", "Perempuan" }));
        ProfilePanel.add(jcJenisKelamin);
        jcJenisKelamin.setBounds(300, 280, 230, 30);

        jtaAlamatProfile.setColumns(20);
        jtaAlamatProfile.setRows(5);
        jtaAlamatProfile.setBorder(null);
        jScrollPane8.setViewportView(jtaAlamatProfile);

        ProfilePanel.add(jScrollPane8);
        jScrollPane8.setBounds(300, 330, 210, 150);

        tfNoTelpProfile.setBorder(null);
        tfNoTelpProfile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNoTelpProfileKeyTyped(evt);
            }
        });
        ProfilePanel.add(tfNoTelpProfile);
        tfNoTelpProfile.setBounds(300, 500, 230, 30);

        jpPasswordProfile.setBorder(null);
        ProfilePanel.add(jpPasswordProfile);
        jpPasswordProfile.setBounds(300, 160, 230, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        ProfilePanel.add(jScrollPane1);
        jScrollPane1.setBounds(610, 90, 490, 350);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/Profile.png"))); // NOI18N
        ProfilePanel.add(jLabel3);
        jLabel3.setBounds(0, 0, 1150, 650);

        MainPanel.add(ProfilePanel, "card6");

        getContentPane().add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1150, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        dispose();
        Login.summonLoginPanel();
    }//GEN-LAST:event_formWindowClosing

    private void desainTabel() {
        DataProductTable.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        DataProductTable.getTableHeader().setOpaque(false);
        DataProductTable.setBackground(Color.WHITE);
        DataProductTable.getTableHeader().setForeground(Color.PINK);
        DataProductTable.setRowHeight(25);

        DataTransactionTable.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        DataTransactionTable.getTableHeader().setOpaque(false);
        DataTransactionTable.setBackground(Color.WHITE);
        DataTransactionTable.getTableHeader().setForeground(Color.PINK);
        DataTransactionTable.setRowHeight(25);

        CashierTable.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        CashierTable.getTableHeader().setOpaque(false);
        CashierTable.setBackground(Color.WHITE);
        CashierTable.getTableHeader().setForeground(Color.PINK);
        CashierTable.setRowHeight(25);

        MemberTable.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 14));
        MemberTable.getTableHeader().setOpaque(false);
        MemberTable.setBackground(Color.WHITE);
        MemberTable.getTableHeader().setForeground(Color.PINK);
        MemberTable.setRowHeight(25);

    }


    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        jLabel1.setText("Hi, " + Encapsulation.getName());
        MainPanelAdmin.removeAll();
        MainPanelAdmin.repaint();
        MainPanelAdmin.revalidate();

        MainPanelAdmin.add(TransactionTablePanel);
        MainPanelAdmin.repaint();
        MainPanelAdmin.revalidate();

        tvDataTransaction.setForeground(utama);
        tvDataProduct.setForeground(klik);

        EnableMember(1);
        EnableKasir(1);
        EnableProfile(1);
    }//GEN-LAST:event_formWindowOpened

    private void tvUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tvUserMouseClicked
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();

        MainPanel.add(ProfilePanel);
        MainPanel.repaint();
        MainPanel.revalidate();

        imgLogo.setForeground(utama);
        tvData.setForeground(utama);

        tvCashier.setForeground(utama);
        tvMember.setForeground(utama);
        tvUser.setForeground(klik);
    }//GEN-LAST:event_tvUserMouseClicked

    private void tvMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tvMemberMouseClicked
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();

        MainPanel.add(MemberPanel);
        MainPanel.repaint();
        MainPanel.revalidate();

        tvMember.setForeground(klik);
        imgLogo.setForeground(utama);
        tvData.setForeground(utama);
        tvCashier.setForeground(utama);
        tvUser.setForeground(utama);

    }//GEN-LAST:event_tvMemberMouseClicked

    private void tvCashierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tvCashierMouseClicked
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();

        MainPanel.add(CashierPanel);
        MainPanel.repaint();
        MainPanel.revalidate();

        imgLogo.setForeground(utama);
        tvData.setForeground(utama);

        tvCashier.setForeground(klik);
        tvMember.setForeground(utama);
        tvUser.setForeground(utama);
    }//GEN-LAST:event_tvCashierMouseClicked

    private void imgLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgLogoMouseClicked
        AboutPanel.summonAboutPanel();
    }//GEN-LAST:event_imgLogoMouseClicked

    private void tvDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tvDataMouseClicked
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();

        MainPanel.add(DataPanel);
        MainPanel.repaint();
        MainPanel.revalidate();

        tvData.setForeground(klik);
        imgLogo.setForeground(utama);
        tvCashier.setForeground(utama);
        tvMember.setForeground(utama);
        tvUser.setForeground(utama);

    }//GEN-LAST:event_tvDataMouseClicked

    private void imgLogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgLogoMouseEntered
        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/logoGlow.png")));
    }//GEN-LAST:event_imgLogoMouseEntered

    private void imgLogoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgLogoMouseExited
        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/logo.png")));
    }//GEN-LAST:event_imgLogoMouseExited

    private void tvDataTransactionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tvDataTransactionMouseClicked
        MainPanelAdmin.removeAll();
        MainPanelAdmin.repaint();
        MainPanelAdmin.revalidate();

        MainPanelAdmin.add(TransactionTablePanel);
        MainPanelAdmin.repaint();
        MainPanelAdmin.revalidate();

        tvDataTransaction.setForeground(utama);
        tvDataProduct.setForeground(klik);

        refreshData(1);

    }//GEN-LAST:event_tvDataTransactionMouseClicked

    private void tvDataProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tvDataProductMouseClicked
        MainPanelAdmin.removeAll();
        MainPanelAdmin.repaint();
        MainPanelAdmin.revalidate();

        MainPanelAdmin.add(ProductTablePanel);
        MainPanelAdmin.repaint();
        MainPanelAdmin.revalidate();

        tvDataTransaction.setForeground(klik);
        tvDataProduct.setForeground(utama);
    }//GEN-LAST:event_tvDataProductMouseClicked

    private void tfMemberIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMemberIdKeyTyped
        if (tfMemberId.getText().length() == 5) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Member Id Melebihi 5 karakter", "Informasi", JOptionPane.WARNING_MESSAGE);

        }

        char angka = evt.getKeyChar();

        if (!(Character.isDigit(angka) || angka == KeyEvent.VK_BACK_SPACE || angka == KeyEvent.VK_DELETE)) {

            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(this, "Inputan Harus Berbentuk Angka", "Informasi", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_tfMemberIdKeyTyped

    private void tfNamaMemberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNamaMemberKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaMemberKeyTyped

    private void tfMemberIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMemberIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMemberIdActionPerformed

    private void tfNoTelponMmberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNoTelponMmberKeyTyped
        if (tfNoTelponMmber.getText().length() == 13) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Product Id Melebihi 13 karakter", "Informasi", JOptionPane.WARNING_MESSAGE);

        }

        char angka = evt.getKeyChar();

        if (!(Character.isDigit(angka) || angka == KeyEvent.VK_BACK_SPACE || angka == KeyEvent.VK_DELETE || angka == KeyEvent.VK_ENTER)) {

            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(this, "Inputan Harus Berbentuk Angka", "Informasi", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_tfNoTelponMmberKeyTyped

    private void btnBaruMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaruMemberActionPerformed
        EnableMember(2);
    }//GEN-LAST:event_btnBaruMemberActionPerformed

    private void btnSimpanMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanMemberActionPerformed
        if (tfMemberId.getText().equals("")){
            JOptionPane.showMessageDialog(this, " Member Id Tidak Boleh Kosong", "Informasi", JOptionPane.WARNING_MESSAGE);
             tfMemberId.requestFocus();
        
        }else if (tfNamaMember.getText().equals("")){
             JOptionPane.showMessageDialog(this, " Nama Member Tidak Boleh Kosong", "Informasi", JOptionPane.WARNING_MESSAGE);
             tfNamaMember.requestFocus();
        
        }else if (jcJenisKelaminMember.getSelectedItem().equals("Pilih Jenis Kelamin")){
            JOptionPane.showMessageDialog(this, " Nama Member Tidak Boleh Kosong", "Informasi", JOptionPane.WARNING_MESSAGE);
             jcJenisKelaminMember.requestFocus();
        
        }else if (taaAlamatMember.getText().equals("")){
            JOptionPane.showMessageDialog(this, " Alamat Tidak Boleh Kosong", "Informasi", JOptionPane.WARNING_MESSAGE);
             tfNamaMember.requestFocus();
        
        }else if (tfNoTelponMmber.getText().equals("")){
            JOptionPane.showMessageDialog(this, " No Telpon Tidak Boleh Kosong", "Informasi", JOptionPane.WARNING_MESSAGE);
             tfNoTelponMmber.requestFocus();
        }
        
        btnSimpanMember.requestFocus();
        EnableMember(1);
        bersihkan();

    }//GEN-LAST:event_btnSimpanMemberActionPerformed

    private void MemberTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MemberTableMouseClicked
        EnableMember(4);
    }//GEN-LAST:event_MemberTableMouseClicked

    private void btnUbahMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahMemberActionPerformed
        EnableMember(5);
    }//GEN-LAST:event_btnUbahMemberActionPerformed

    private void btnHapusMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusMemberActionPerformed
        EnableMember(6);
    }//GEN-LAST:event_btnHapusMemberActionPerformed

    private void btnBatalMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalMemberActionPerformed
        EnableMember(7);
    }//GEN-LAST:event_btnBatalMemberActionPerformed

    private void tfNamaKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaKasirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaKasirActionPerformed

    private void btnBaruKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaruKasirActionPerformed
        EnableKasir(2);
    }//GEN-LAST:event_btnBaruKasirActionPerformed

    private void btnSimpanKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanKasirActionPerformed
        if (tfUsernameKasir.getText().equals("")){
             JOptionPane.showMessageDialog(this, " Username Tidak Boleh Kosong", "Informasi", JOptionPane.WARNING_MESSAGE);
             tfUsernameKasir.requestFocus();
        
        }else if (jpPasswordKasir.getText().equals("")){
              JOptionPane.showMessageDialog(this, " Password Tidak Boleh Kosong", "Informasi", JOptionPane.WARNING_MESSAGE);
             jpPasswordKasir.requestFocus();
            
        }else if (tfNamaKasir.getText().equals("")){
            JOptionPane.showMessageDialog(this, " Nama Tidak Boleh Kosong", "Informasi", JOptionPane.WARNING_MESSAGE);
             tfNamaKasir.requestFocus();
            
        }else if (jcJenisKleaminKaisr.getSelectedItem().equals("Pilih Jenis Kelamin")){
             JOptionPane.showMessageDialog(this, " Jenis Kelamin Tidak Boleh Kosong", "Informasi", JOptionPane.WARNING_MESSAGE);
             jcJenisKleaminKaisr.requestFocus();
        
        }else if (taAlamatKasir.getText().equals("")){
             JOptionPane.showMessageDialog(this, " Jenis Kelamin Tidak Boleh Kosong", "Informasi", JOptionPane.WARNING_MESSAGE);
             taAlamatKasir.requestFocus();
        
        }else if (tfNoTelpKasir.getText().equals("")){
             JOptionPane.showMessageDialog(this, " No Telpon Tidak Boleh Kosong", "Informasi", JOptionPane.WARNING_MESSAGE);
             tfNoTelponMmber.requestFocus();
        }else {
             
        }
          EnableKasir(1);
        
       
    }//GEN-LAST:event_btnSimpanKasirActionPerformed

    private void CashierTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CashierTableMouseClicked
        EnableKasir(4);
    }//GEN-LAST:event_CashierTableMouseClicked

    private void btnUbahKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahKasirActionPerformed
        EnableKasir(5);
    }//GEN-LAST:event_btnUbahKasirActionPerformed

    private void btnHapusKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusKasirActionPerformed
        EnableKasir(6);
    }//GEN-LAST:event_btnHapusKasirActionPerformed

    private void btnBatalKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalKasirActionPerformed
        EnableKasir(7);
    }//GEN-LAST:event_btnBatalKasirActionPerformed

    private void btnSimpanProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanProfileActionPerformed
         if (tfUsernameProfile.getText().equals("")){
             JOptionPane.showMessageDialog(this, " Username Tidak Boleh Kosong", "Informasi", JOptionPane.WARNING_MESSAGE);
             tfUsernameProfile.requestFocus();
         
         }else if (jpPasswordProfile.getText().equals("")){
             JOptionPane.showMessageDialog(this, "Password Tidak Boleh Kosong", "Informasi", JOptionPane.WARNING_MESSAGE);
              jpPasswordProfile.requestFocus();
         }else if (tfNamaProfile.getText().equals("")){
             JOptionPane.showMessageDialog(this, "Nama Tidak Boleh Kosong", "Informasi", JOptionPane.WARNING_MESSAGE);
              tfNamaProfile.requestFocus();
         
         }else if (jcJenisKelamin.getSelectedItem().equals("Pilih Jenis Kelamin")){
             JOptionPane.showMessageDialog(this, "jenis Kelamin Tidak Boleh Kosong", "Informasi", JOptionPane.WARNING_MESSAGE);
              jcJenisKelamin.requestFocus();
         }else if (jtaAlamatProfile.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Alamat Tidak Boleh Kosong", "Informasi", JOptionPane.WARNING_MESSAGE);
              jtaAlamatProfile.requestFocus(); 
         }else if (tfNoTelpProfile.getText().equals("")){
              JOptionPane.showMessageDialog(this, "Alamat Tidak Boleh Kosong", "Informasi", JOptionPane.WARNING_MESSAGE);
               tfNoTelpProfile.requestFocus(); 
         }else {
             
         }
     btnSimpanProfile.requestFocus();
        EnableProfile(1);
        bersihkan();
    }//GEN-LAST:event_btnSimpanProfileActionPerformed

    private void btnHapusProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusProfileActionPerformed
        EnableProfile(1);
    }//GEN-LAST:event_btnHapusProfileActionPerformed

    private void btnUbahProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahProfileActionPerformed
        EnableProfile(2);
    }//GEN-LAST:event_btnUbahProfileActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        this.dispose();
        Login.summonLoginPanel();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jcJenisKleaminKaisrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcJenisKleaminKaisrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcJenisKleaminKaisrActionPerformed

    private void tfNoTelpKasirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNoTelpKasirKeyTyped
          char angka = evt.getKeyChar();

        if (!(Character.isDigit(angka) || angka == KeyEvent.VK_BACK_SPACE || angka == KeyEvent.VK_DELETE || angka == KeyEvent.VK_ENTER)) {

            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(this, "Inputan Harus Berbentuk Angka", "Informasi", JOptionPane.WARNING_MESSAGE);
        }
        
         
        if (tfNoTelpKasir.getText().length() > 13  ) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "No Telp Melebihi 13 karakter", "Informasi", JOptionPane.WARNING_MESSAGE);
            
            btnSimpanKasir.requestFocus();
        }
    }//GEN-LAST:event_tfNoTelpKasirKeyTyped

    private void tfUsernameKasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUsernameKasirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUsernameKasirActionPerformed

    private void tfNoTelpProfileKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNoTelpProfileKeyTyped
          if (tfNoTelpProfile.getText().length() == 13) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "No Telpon Melebihi 13 karakter", "Informasi", JOptionPane.WARNING_MESSAGE);

        }

        char angka = evt.getKeyChar();

        if (!(Character.isDigit(angka) || angka == KeyEvent.VK_BACK_SPACE || angka == KeyEvent.VK_DELETE || angka == KeyEvent.VK_ENTER)) {

            getToolkit().beep();
            evt.consume();

            JOptionPane.showMessageDialog(this, "Inputan Harus Berbentuk Angka", "Informasi", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_tfNoTelpProfileKeyTyped

    private void EnableKasir(int mode) {
        if (mode == 1) {
            //windows opened
            tfUsernameKasir.setEditable(false);
            tfNamaKasir.setEditable(false);
            jpPasswordKasir.setEditable(false);
            jcJenisKleaminKaisr.setEnabled(false);
            taAlamatKasir.setEnabled(false);
            tfNoTelpKasir.setEditable(false);

            btnBaruKasir.setEnabled(true);
            btnSimpanKasir.setEnabled(false);
            btnUbahKasir.setEnabled(false);
            btnHapusKasir.setEnabled(false);
            btnBatalKasir.setEnabled(false);
            btnBaruKasir.requestFocus();
            bersihkan();

        } else if (mode == 2) {
            //btnBaru
            tfUsernameKasir.setEditable(true);
            tfNamaKasir.setEditable(true);
            jpPasswordKasir.setEditable(true);
            jcJenisKleaminKaisr.setEnabled(true);
            taAlamatKasir.setEnabled(true);
            tfNoTelpKasir.setEditable(true);

            btnBaruKasir.setEnabled(false);
            btnSimpanKasir.setEnabled(true);
            btnUbahKasir.setEnabled(false);
            btnHapusKasir.setEnabled(false);
            btnBatalKasir.setEnabled(true);
            btnSimpanKasir.requestFocus();
            tfUsernameKasir.requestFocus();
            jpPasswordProfile.requestFocus();

        } else if (mode == 4) {

            //klik tabel
            tfUsernameKasir.setEditable(false);
            tfNamaKasir.setEditable(false);
            jpPasswordKasir.setEditable(false);
            jcJenisKleaminKaisr.setEnabled(false);
            taAlamatKasir.setEnabled(false);
            tfNoTelpKasir.setEditable(false);

            btnBaruKasir.setEnabled(false);
            btnSimpanKasir.setEnabled(false);
            btnUbahKasir.setEnabled(true);
            btnHapusKasir.setEnabled(true);
            btnBatalKasir.setEnabled(true);
            btnUbahKasir.requestFocus();

        } else if (mode == 5) {
            //ubah
            tfUsernameKasir.setEditable(false);
            jpPasswordKasir.setEditable(true);
            jcJenisKleaminKaisr.setEnabled(true);
            taAlamatKasir.setEnabled(true);
            tfNoTelpKasir.setEditable(true);
            tfNamaKasir.setEditable(true);

            btnBaruKasir.setEnabled(false);
            btnSimpanKasir.setEnabled(true);
            btnUbahKasir.setEnabled(false);
            btnHapusKasir.setEnabled(false);
            btnBatalKasir.setEnabled(true);
            btnSimpanKasir.requestFocus();
            jpPasswordKasir.requestFocus();

        } else if (mode == 6) {
            //hapus
            tfUsernameKasir.setEditable(false);
            tfNamaKasir.setEditable(false);
            jpPasswordKasir.setEditable(false);
            jcJenisKleaminKaisr.setEnabled(false);
            taAlamatKasir.setEnabled(false);
            tfNoTelpKasir.setEditable(false);

            btnBaruKasir.setEnabled(true);
            btnSimpanKasir.setEnabled(false);
            btnUbahKasir.setEnabled(false);
            btnHapusKasir.setEnabled(false);
            btnBatalKasir.setEnabled(false);
            btnBatalKasir.requestFocus();

        } else if (mode == 7) {

            //batal
            tfUsernameKasir.setEditable(false);
            tfNamaKasir.setEditable(false);
            jpPasswordKasir.setEditable(false);
            jcJenisKleaminKaisr.setEnabled(false);
            taAlamatKasir.setEnabled(false);
            tfNoTelpKasir.setEditable(false);

            btnBaruKasir.setEnabled(true);
            btnSimpanKasir.setEnabled(false);
            btnUbahKasir.setEnabled(false);
            btnHapusKasir.setEnabled(false);
            btnBatalKasir.setEnabled(false);
            btnSimpanKasir.requestFocus();
            tfUsernameKasir.requestFocus();
            bersihkan();

        }

    }

    private void EnableMember(int mode) {
        if (mode == 1) {

            //windows opened
            tfMemberId.setEditable(false);
            tfNamaMember.setEditable(false);
            jcJenisKelaminMember.setEnabled(false);
            taaAlamatMember.setEnabled(false);

            tfNoTelponMmber.setEditable(false);

            btnBaruMember.setEnabled(true);
            btnSimpanMember.setEnabled(false);
            btnUbahMember.setEnabled(false);
            btnHapusMember.setEnabled(false);
            btnBatalMember.setEnabled(false);

            btnBaruMember.requestFocus();
            bersihkan();

        } else if (mode == 2) {

            //btn baru ketika di klik 
            tfMemberId.setEditable(true);
            tfNamaMember.setEditable(true);
            jcJenisKelaminMember.setEnabled(true);
            taaAlamatMember.setEnabled(true);
            tfNoTelponMmber.setEditable(true);

            btnBaruMember.setEnabled(false);
            btnSimpanMember.setEnabled(true);
            btnUbahMember.setEnabled(false);
            btnHapusMember.setEnabled(false);
            btnBatalMember.setEnabled(true);
            btnSimpanMember.requestFocus();
            tfMemberId.requestFocus();
            bersihkan();

        } else if (mode == 3) {
            //btn simpan ketika di klik 
            tfMemberId.setEditable(false);
            tfNamaMember.setEditable(false);
            jcJenisKelaminMember.setEnabled(false);
            taaAlamatMember.setEnabled(false);
            tfNoTelponMmber.setEditable(false);

            btnBaruMember.setEnabled(true);
            btnSimpanMember.setEnabled(false);
            btnUbahMember.setEnabled(false);
            btnHapusMember.setEnabled(false);
            btnBatalMember.setEnabled(false);
            btnBaruMember.requestFocus();

        } else if (mode == 4) {
            //klik di tabel
            tfMemberId.setEditable(false);
            tfNamaMember.setEditable(true);
            jcJenisKelaminMember.setEnabled(true);
            taaAlamatMember.setEnabled(true);
            tfNoTelponMmber.setEditable(true);

            btnBaruMember.setEnabled(false);
            btnSimpanMember.setEnabled(false);
            btnUbahMember.setEnabled(true);
            btnHapusMember.setEnabled(true);
            btnBatalMember.setEnabled(true);
            btnUbahMember.requestFocus();

        } else if (mode == 5) {

            //ubah
            tfMemberId.setEditable(false);
            tfNamaMember.setEditable(true);
            jcJenisKelaminMember.setEnabled(true);
            taaAlamatMember.setEnabled(true);
            tfNoTelponMmber.setEditable(true);

            btnBaruMember.setEnabled(false);
            btnSimpanMember.setEnabled(true);
            btnUbahMember.setEnabled(false);
            btnHapusMember.setEnabled(false);
            btnBatalMember.setEnabled(true);
            btnSimpanMember.requestFocus();
            tfNamaMember.requestFocus();

        } else if (mode == 6) {
            //hapus
            tfMemberId.setEditable(false);
            tfNamaMember.setEditable(false);
            jcJenisKelaminMember.setEnabled(false);
            taaAlamatMember.setEnabled(false);
            tfNoTelponMmber.setEditable(false);

            btnBaruMember.setEnabled(true);
            btnSimpanMember.setEnabled(false);
            btnUbahMember.setEnabled(false);
            btnHapusMember.setEnabled(false);
            btnBatalMember.setEnabled(false);
            btnBaruMember.requestFocus();

        } else if (mode == 7) {

            //batal
            tfMemberId.setEditable(false);
            tfNamaMember.setEditable(false);
            jcJenisKelaminMember.setEnabled(false);
            taaAlamatMember.setEditable(false);
            tfNoTelponMmber.setEditable(false);

            btnBaruMember.setEnabled(true);
            btnSimpanMember.setEnabled(false);
            btnUbahMember.setEnabled(false);
            btnHapusMember.setEnabled(false);
            btnBatalMember.setEnabled(false);
            btnSimpanMember.requestFocus();
            tfMemberId.requestFocus();
            bersihkan();

        }
    }

    private void EnableProfile(int model) {
        //ketika frmae pertama kali di buka
        if (model == 1) {
            //ketika frmae pertama kali di buka
            btnUbahProfile.setEnabled(true);
            btnSimpanProfile.setEnabled(false);
            btnHapusProfile.setEnabled(false);

            tfUsernameProfile.setEditable(false);
            tfNamaProfile.setEditable(false);
            jpPasswordProfile.setEditable(false);
            jcJenisKelamin.setEditable(false);
            jtaAlamatProfile.setEditable(false);
            tfNoTelpProfile.setEditable(false);

        } else if (model == 2) {
            //btn ubah 
            btnUbahProfile.setEnabled(false);
            btnSimpanProfile.setEnabled(true);
            btnHapusProfile.setEnabled(true);

            tfUsernameProfile.setEditable(false);
            tfNamaProfile.setEditable(true);
            jpPasswordProfile.setEditable(true);
            jcJenisKelamin.setEditable(true);
            jtaAlamatProfile.setEditable(true);
            tfNoTelpProfile.setEditable(true);
            jpPasswordProfile.requestFocus();

        }

    }

    private void bersihkan() {
        tfUsernameProfile.setText("");
        jpPasswordProfile.setText("");
        tfNamaProfile.setText("");
//          jcJenisKelaminProfile.setSelectedItem("");
        jtaAlamatProfile.setText("");
        jtaAlamatProfile.setText("");

        tfMemberId.setText("");
        tfNamaMember.setText("");
//          jcJenisKelaminMember.
        taaAlamatMember.setText("");
        tfNoTelponMmber.setText("");

        tfUsernameKasir.setText("");
        jpPasswordKasir.setText("");
        tfNamaKasir.setText("");
//          jcJenisKleaminKaisr

        taAlamatKasir.setText("");
        tfNoTelpKasir.setText("");

    }

    private void refreshData(int mode) {
        if (mode == 1) {
            try {
                dataTransactionTable.getDataVector().removeAllElements();
                dataTransactionTable.fireTableDataChanged();
                hasil = AppDatabase.perintah.executeQuery("Select invoice_number, employee.name as cashier, "
                        + "customer.name as member, date, product.name as product, qty, price*qty as pembayaran "
                        + "from customer join invoice using(customer_id) "
                        + " join employee using(username) "
                        + " join transaction using(invoice_number)"
                        + " join product using(product_id)"
                        + " order by invoice_number");
                while (hasil.next()) {
                    dataTransactionTable.addRow(new Object[]{
                        hasil.getString("invoice_number"),
                        hasil.getString("cashier"),
                        hasil.getString("member"),
                        hasil.getString("date"),
                        hasil.getString("product"),
                        hasil.getString("qty"),
                        hasil.getString("pembayaran")
                    });
                }
            } catch (SQLException e) {
                System.err.println("Query Select Data Transaksi Gagal");
            }
        } else if (mode == 2){
            
        }
    }

    public static void summonAdminPanel() {
        AdminPanel adminPanel = new AdminPanel();
        adminPanel.setSize(1150, 695);
        adminPanel.setLocationRelativeTo(null);
        adminPanel.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                summonAdminPanel();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CashierPanel;
    private javax.swing.JTable CashierTable;
    private javax.swing.JPanel DataPanel;
    private javax.swing.JTable DataProductTable;
    private javax.swing.JTable DataTransactionTable;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel MainPanelAdmin;
    private javax.swing.JPanel MemberPanel;
    private javax.swing.JTable MemberTable;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JPanel ProductTablePanel;
    private javax.swing.JPanel ProfilePanel;
    private javax.swing.JPanel TransactionTablePanel;
    private javax.swing.JPanel WelcomePanel;
    private javax.swing.JButton btnBaruKasir;
    private javax.swing.JButton btnBaruMember;
    private javax.swing.JButton btnBatalKasir;
    private javax.swing.JButton btnBatalMember;
    private javax.swing.JButton btnHapusKasir;
    private javax.swing.JButton btnHapusMember;
    private javax.swing.JButton btnHapusProfile;
    private javax.swing.JButton btnSimpanKasir;
    private javax.swing.JButton btnSimpanMember;
    private javax.swing.JButton btnSimpanProfile;
    private javax.swing.JButton btnUbahKasir;
    private javax.swing.JButton btnUbahMember;
    private javax.swing.JButton btnUbahProfile;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JLabel imgWelcome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> jcJenisKelamin;
    private javax.swing.JComboBox<String> jcJenisKelaminMember;
    private javax.swing.JComboBox<String> jcJenisKleaminKaisr;
    private javax.swing.JTextField jpPasswordKasir;
    private javax.swing.JPasswordField jpPasswordProfile;
    private javax.swing.JTextArea jtaAlamatProfile;
    private javax.swing.JTextArea taAlamatKasir;
    private javax.swing.JTextArea taaAlamatMember;
    private javax.swing.JTextField tfMemberId;
    private javax.swing.JTextField tfNamaKasir;
    private javax.swing.JTextField tfNamaMember;
    private javax.swing.JTextField tfNamaProfile;
    private javax.swing.JTextField tfNoTelpKasir;
    private javax.swing.JTextField tfNoTelpProfile;
    private javax.swing.JTextField tfNoTelponMmber;
    private javax.swing.JTextField tfUsernameKasir;
    private javax.swing.JTextField tfUsernameProfile;
    private javax.swing.JLabel tvCashier;
    private javax.swing.JLabel tvData;
    private javax.swing.JLabel tvDataProduct;
    private javax.swing.JLabel tvDataTransaction;
    private javax.swing.JLabel tvMember;
    private javax.swing.JLabel tvUser;
    // End of variables declaration//GEN-END:variables
}
