/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Color;
import java.awt.color.ColorSpace;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author muham
 */
public class CashierPanel extends javax.swing.JFrame {

    Color klik;
    Color utama;

    /**
     * Creates new form CashierPanel
     */
    public CashierPanel() {
        initComponents();

        klik = Color.BLUE;
        utama = new Color(250,128,114);

        tvUser.setForeground(utama);
        tvTransaction.setForeground(utama);
        tvMember.setForeground(utama);
        tvProduct.setForeground(utama);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        MenuPanel = new javax.swing.JPanel();
        tvUser = new javax.swing.JLabel();
        tvTransaction = new javax.swing.JLabel();
        tvMember = new javax.swing.JLabel();
        tvProduct = new javax.swing.JLabel();
        tvAbout = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        welcomePanel = new javax.swing.JPanel();
        tvWelcome = new javax.swing.JLabel();
        imgWelcome = new javax.swing.JLabel();
        ProfilePanel = new javax.swing.JPanel();
        jtNama = new javax.swing.JTextField();
        jpPassword = new javax.swing.JPasswordField();
        jtUsername = new javax.swing.JTextField();
        jsGender = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jaAlamat = new javax.swing.JTextArea();
        jtNoTelp = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        imgTransaction = new javax.swing.JLabel();
        transaksiPanel = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jtCustomerId = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        tfInvoiceNumber = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tfProductId = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        label = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        memberRegisterPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        inputMain = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        PanelInput = new javax.swing.JPanel();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField14 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        InputPanel = new javax.swing.JPanel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        imgProduct = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuPanel.setBackground(new java.awt.Color(255, 255, 255));
        MenuPanel.setForeground(new java.awt.Color(255, 255, 255));

        tvUser.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tvUser.setForeground(new java.awt.Color(250, 128, 114));
        tvUser.setText("Hi, User");
        tvUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tvUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tvUserMouseClicked(evt);
            }
        });

        tvTransaction.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tvTransaction.setForeground(new java.awt.Color(250, 128, 114));
        tvTransaction.setText(" Transaction");
        tvTransaction.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tvTransaction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tvTransactionMouseClicked(evt);
            }
        });

        tvMember.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tvMember.setForeground(new java.awt.Color(250, 128, 114));
        tvMember.setText("Member");
        tvMember.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tvMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tvMemberMouseClicked(evt);
            }
        });

        tvProduct.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tvProduct.setForeground(new java.awt.Color(250, 128, 114));
        tvProduct.setText("Product");
        tvProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tvProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tvProductMouseClicked(evt);
            }
        });

        tvAbout.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tvAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/logo.png"))); // NOI18N
        tvAbout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tvAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tvAboutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tvAboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tvAboutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tvAbout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 327, Short.MAX_VALUE)
                .addComponent(tvTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(tvProduct)
                .addGap(40, 40, 40)
                .addComponent(tvMember)
                .addGap(210, 210, 210)
                .addComponent(tvUser, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuPanelLayout.createSequentialGroup()
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tvProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MenuPanelLayout.createSequentialGroup()
                        .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tvUser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MenuPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(tvMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(tvTransaction, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tvAbout, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(MenuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        mainPanel.setBackground(new java.awt.Color(51, 255, 153));
        mainPanel.setLayout(new java.awt.CardLayout());

        welcomePanel.setBackground(new java.awt.Color(255, 255, 255));
        welcomePanel.setLayout(null);

        tvWelcome.setFont(new java.awt.Font("Dialog", 1, 28)); // NOI18N
        tvWelcome.setForeground(new java.awt.Color(255, 255, 255));
        tvWelcome.setText("Your Name");
        welcomePanel.add(tvWelcome);
        tvWelcome.setBounds(40, 280, 430, 60);

        imgWelcome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/welcome.png"))); // NOI18N
        welcomePanel.add(imgWelcome);
        imgWelcome.setBounds(0, 0, 1150, 650);

        mainPanel.add(welcomePanel, "card2");

        ProfilePanel.setBackground(new java.awt.Color(51, 255, 204));
        ProfilePanel.setLayout(null);

        jtNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtNamaKeyTyped(evt);
            }
        });
        ProfilePanel.add(jtNama);
        jtNama.setBounds(300, 220, 240, 33);

        jpPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jpPasswordKeyTyped(evt);
            }
        });
        ProfilePanel.add(jpPassword);
        jpPassword.setBounds(300, 160, 240, 33);

        jtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtUsernameKeyTyped(evt);
            }
        });
        ProfilePanel.add(jtUsername);
        jtUsername.setBounds(300, 100, 240, 33);

        jsGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gender", "Laki-Laki", "Perempuan" }));
        ProfilePanel.add(jsGender);
        jsGender.setBounds(310, 270, 220, 33);

        jaAlamat.setColumns(20);
        jaAlamat.setRows(5);
        jaAlamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jaAlamatKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jaAlamat);

        ProfilePanel.add(jScrollPane1);
        jScrollPane1.setBounds(300, 330, 220, 150);

        jtNoTelp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtNoTelpKeyTyped(evt);
            }
        });
        ProfilePanel.add(jtNoTelp);
        jtNoTelp.setBounds(300, 500, 230, 33);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        ProfilePanel.add(btnSave);
        btnSave.setBounds(630, 480, 115, 41);

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        ProfilePanel.add(btnBatal);
        btnBatal.setBounds(770, 480, 115, 41);

        imgTransaction.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        imgTransaction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/CashierProfile.png"))); // NOI18N
        ProfilePanel.add(imgTransaction);
        imgTransaction.setBounds(0, 0, 1155, 650);

        mainPanel.add(ProfilePanel, "card3");

        transaksiPanel.setBackground(new java.awt.Color(255, 255, 0));
        transaksiPanel.setLayout(null);

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        transaksiPanel.add(jTextField1);
        jTextField1.setBounds(870, 120, 129, 24);

        jtCustomerId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtCustomerIdKeyTyped(evt);
            }
        });
        transaksiPanel.add(jtCustomerId);
        jtCustomerId.setBounds(730, 20, 136, 24);

        jButton1.setText("Go");
        transaksiPanel.add(jButton1);
        jButton1.setBounds(910, 20, 45, 32);

        tfInvoiceNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfInvoiceNumberKeyTyped(evt);
            }
        });
        transaksiPanel.add(tfInvoiceNumber);
        tfInvoiceNumber.setBounds(280, 20, 129, 24);

        jLabel13.setText("jLabel13");
        transaksiPanel.add(jLabel13);
        jLabel13.setBounds(380, 130, 48, 16);

        jLabel15.setText("jLabel15");
        transaksiPanel.add(jLabel15);
        jLabel15.setBounds(630, 130, 48, 16);

        jLabel17.setText("jLabel17");
        transaksiPanel.add(jLabel17);
        jLabel17.setBounds(780, 130, 48, 16);

        tfProductId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfProductIdKeyTyped(evt);
            }
        });
        transaksiPanel.add(tfProductId);
        tfProductId.setBounds(70, 130, 129, 24);

        jButton2.setText("Enter");
        transaksiPanel.add(jButton2);
        jButton2.setBounds(1020, 110, 60, 32);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Product", "Jumlah", "Harga Satuan", "Total Harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        transaksiPanel.add(jScrollPane2);
        jScrollPane2.setBounds(40, 190, 1070, 280);

        jLabel21.setText("jLabel21");
        transaksiPanel.add(jLabel21);
        jLabel21.setBounds(890, 480, 70, 16);

        jTextField5.setText("jTextField5");
        transaksiPanel.add(jTextField5);
        jTextField5.setBounds(890, 550, 80, 28);

        label.setText("label");
        transaksiPanel.add(label);
        label.setBounds(890, 610, 70, 16);

        jButton3.setText("Transaksi Batal");
        transaksiPanel.add(jButton3);
        jButton3.setBounds(221, 527, 119, 32);

        jButton4.setText("Transaksi Selesai");
        transaksiPanel.add(jButton4);
        jButton4.setBounds(358, 527, 132, 32);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/TransactionPanel.png"))); // NOI18N
        transaksiPanel.add(jLabel9);
        jLabel9.setBounds(0, 0, 1330, 650);

        mainPanel.add(transaksiPanel, "card4");

        memberRegisterPanel.setBackground(new java.awt.Color(0, 255, 0));
        memberRegisterPanel.setLayout(null);

        jLabel11.setText("Nama");
        memberRegisterPanel.add(jLabel11);
        jLabel11.setBounds(174, 135, 33, 16);

        jLabel44.setText("Alamat");
        memberRegisterPanel.add(jLabel44);
        jLabel44.setBounds(174, 169, 40, 16);

        jLabel45.setText("Jenis Kelamin");
        memberRegisterPanel.add(jLabel45);
        jLabel45.setBounds(174, 254, 80, 16);

        inputMain.setBackground(new java.awt.Color(0, 102, 102));
        inputMain.setLayout(new java.awt.CardLayout());

        jPanel4.setBackground(new java.awt.Color(204, 102, 255));

        jLabel46.setText("jLabel46");

        jLabel47.setText("jLabel47");

        jLabel48.setText("jLabel48");

        jLabel49.setText("jLabel49");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel46)
                .addGap(18, 18, 18)
                .addComponent(jLabel47)
                .addGap(18, 18, 18)
                .addComponent(jLabel48)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jLabel49)
                .addGap(30, 30, 30))
        );

        inputMain.add(jPanel4, "card3");

        jTextField12.setText("jTextField12");
        jTextField12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField12KeyTyped(evt);
            }
        });

        jTextField13.setText("jTextField13");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jTextField14.setText("jTextField14");

        javax.swing.GroupLayout PanelInputLayout = new javax.swing.GroupLayout(PanelInput);
        PanelInput.setLayout(PanelInputLayout);
        PanelInputLayout.setHorizontalGroup(
            PanelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(jTextField13)
                    .addComponent(jTextField12)
                    .addGroup(PanelInputLayout.createSequentialGroup()
                        .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 52, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelInputLayout.setVerticalGroup(
            PanelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInputLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        inputMain.add(PanelInput, "card2");

        memberRegisterPanel.add(inputMain);
        inputMain.setBounds(306, 76, 254, 211);

        jButton9.setText("Edit");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        memberRegisterPanel.add(jButton9);
        jButton9.setBounds(306, 341, 87, 32);

        jButton10.setText("Cancel");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        memberRegisterPanel.add(jButton10);
        jButton10.setBounds(411, 341, 90, 32);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/MemberPanel.png"))); // NOI18N
        jLabel1.setText("Member id");
        memberRegisterPanel.add(jLabel1);
        jLabel1.setBounds(0, 0, 1150, 650);

        mainPanel.add(memberRegisterPanel, "card5");

        InputPanel.setBackground(new java.awt.Color(51, 153, 255));
        InputPanel.setLayout(null);

        jTextField6.setText("jTextField6");
        InputPanel.add(jTextField6);
        jTextField6.setBounds(280, 120, 202, 27);

        jTextField7.setText("jTextField6");
        InputPanel.add(jTextField7);
        jTextField7.setBounds(280, 290, 202, 22);

        jTextField8.setText("jTextField6");
        InputPanel.add(jTextField8);
        jTextField8.setBounds(280, 180, 202, 24);

        jTextField9.setText("jTextField6");
        InputPanel.add(jTextField9);
        jTextField9.setBounds(280, 230, 202, 24);

        jTextField10.setText("jTextField6");
        InputPanel.add(jTextField10);
        jTextField10.setBounds(280, 350, 202, 23);

        jTextField11.setText("jTextField6");
        InputPanel.add(jTextField11);
        jTextField11.setBounds(280, 400, 202, 29);

        jButton5.setText("Batal ");
        InputPanel.add(jButton5);
        jButton5.setBounds(550, 495, 90, 31);

        jButton6.setText("Oke");
        InputPanel.add(jButton6);
        jButton6.setBounds(390, 460, 88, 31);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.setOpaque(false);

        jLabel31.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel31.setText("Konfirmasi");

        jLabel32.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel32.setText("Product Id");

        jLabel33.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel33.setText("Nama");

        jLabel34.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel34.setText("Merek");

        jLabel35.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel35.setText("Jenis");

        jLabel36.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel36.setText("Spek");

        jLabel37.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel37.setText("Harga");

        jLabel38.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel38.setText("jLabel38");

        jLabel39.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel39.setText("jLabel39");

        jLabel40.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel40.setText("jLabel40");

        jLabel41.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel41.setText("jLabel41");

        jLabel42.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel42.setText("jLabel42");

        jLabel43.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel43.setText("jLabel43");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36)
                    .addComponent(jLabel37))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel40, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel31)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel31)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jLabel38))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jLabel39))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel40))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jLabel41))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jLabel42))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(jLabel43))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        InputPanel.add(jPanel1);
        jPanel1.setBounds(550, 120, 275, 348);

        jButton7.setText("Batal");
        InputPanel.add(jButton7);
        jButton7.setBounds(280, 460, 90, 31);

        jButton8.setText("Input");
        InputPanel.add(jButton8);
        jButton8.setBounds(737, 495, 88, 31);

        imgProduct.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        imgProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/ProductPanel.png"))); // NOI18N
        InputPanel.add(imgProduct);
        imgProduct.setBounds(0, 0, 1150, 650);

        mainPanel.add(InputPanel, "card6");

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 56, 1150, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        dispose();
        Login.summonLoginPanel();
    }//GEN-LAST:event_formWindowClosing


    private void tvProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tvProductMouseClicked

        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(InputPanel);
        mainPanel.repaint();
        mainPanel.revalidate();

        tvUser.setForeground(utama);
        tvTransaction.setForeground(utama);
        tvMember.setForeground(utama);
        tvProduct.setForeground(klik);
        tvAbout.setForeground(utama);
    }//GEN-LAST:event_tvProductMouseClicked

    private void tvMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tvMemberMouseClicked
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(memberRegisterPanel);
        mainPanel.repaint();
        mainPanel.revalidate();

        tvUser.setForeground(utama);
        tvTransaction.setForeground(utama);
        tvMember.setForeground(klik);
        tvProduct.setForeground(utama);
        tvAbout.setForeground(utama);
    }//GEN-LAST:event_tvMemberMouseClicked

    private void tvTransactionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tvTransactionMouseClicked
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(transaksiPanel);
        mainPanel.repaint();
        mainPanel.revalidate();

        tvUser.setForeground(utama);
        tvTransaction.setForeground(klik);
        tvMember.setForeground(utama);
        tvProduct.setForeground(utama);
        tvAbout.setForeground(utama);
    }//GEN-LAST:event_tvTransactionMouseClicked

    private void tvUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tvUserMouseClicked

        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();

        mainPanel.add(ProfilePanel);
        mainPanel.repaint();
        mainPanel.revalidate();

        ProfilePanel.setVisible(true);
        MenuPanel.setVisible(true);
        tvUser.setForeground(klik);
        tvTransaction.setForeground(utama);
        tvMember.setForeground(utama);
        tvProduct.setForeground(utama);
        tvAbout.setForeground(utama);
    }//GEN-LAST:event_tvUserMouseClicked

    private void jtUsernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtUsernameKeyTyped

        if (jtUsername.getText().length() > 20) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Username Melebihi 20 karakter", "Informasi", JOptionPane.WARNING_MESSAGE);
             
        }
    }//GEN-LAST:event_jtUsernameKeyTyped

    private void jpPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpPasswordKeyTyped
        if (String.valueOf(jpPassword.getPassword()).length() == 20) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Password Melebihi 20 karakter", "Informasi", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jpPasswordKeyTyped

    private void jtNamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNamaKeyTyped
        if (jtNama.getText().length() > 30) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Nama Melebihi 30 karakter", "Informasi", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jtNamaKeyTyped

    private void jaAlamatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jaAlamatKeyTyped
        if (jaAlamat.getText().length() > 150) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Alamat Melebihi 150 karakter", "Informasi", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jaAlamatKeyTyped

    private void jtNoTelpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtNoTelpKeyTyped

           char angka = evt.getKeyChar();
       
       if (!(Character.isDigit(angka)||angka==KeyEvent.VK_BACK_SPACE||angka==KeyEvent.VK_DELETE)){
           
           getToolkit().beep();
           evt.consume();
            
             JOptionPane.showMessageDialog(this, "Inputan Harus Berbentuk Angka", "Informasi", JOptionPane.WARNING_MESSAGE);
       }
       

        if (jtNoTelp.getText().length() > 13) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "No Telp Melebihi 13 karakter", "Informasi", JOptionPane.WARNING_MESSAGE);

            //buat perkondisian yang busa di inputkan angka ini kan masih bebas angka dan huruf
        }
    }//GEN-LAST:event_jtNoTelpKeyTyped

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        if (jtUsername.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Username Tidak Boleh Kosong", "Informasi", JOptionPane.WARNING_MESSAGE);
            jtUsername.requestFocus();

        } else if (jpPassword.getPassword().equals("")) {
            JOptionPane.showMessageDialog(this, "Password Tidak Boleh Kosong", "Informasi", JOptionPane.WARNING_MESSAGE);
            jpPassword.requestFocus();

        } else if (jtNama.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Nama Tidak Boleh Kosong", "Informasi", JOptionPane.WARNING_MESSAGE);
            jtNama.requestFocus();

            //perkondisian gender
        } else if (jaAlamat.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Alamat Tidak Boleh Kosong", "Informasi", JOptionPane.WARNING_MESSAGE);
            jaAlamat.requestFocus();

        } else if (jtNoTelp.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "N0 Telp Tidak Boleh Kosong", "Informasi", JOptionPane.WARNING_MESSAGE);
            jtNoTelp.requestFocus();

        } else {

        }


    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        bersihkan();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void tvAboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tvAboutMouseEntered
        tvAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/logoGlow.png")));
    }//GEN-LAST:event_tvAboutMouseEntered

    private void tvAboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tvAboutMouseExited
        tvAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/logo.png")));
    }//GEN-LAST:event_tvAboutMouseExited

    private void tvAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tvAboutMouseClicked
        AboutPanel.summonAboutPanel();
    }//GEN-LAST:event_tvAboutMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        tvUser.setText("Hi, " + Encapsulation.getUsername());
        tvWelcome.setText(Encapsulation.getName());
      
        
    }//GEN-LAST:event_formWindowOpened

    private void tfProductIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfProductIdKeyTyped
        
        char angka = evt.getKeyChar();
       
       if (!(Character.isDigit(angka)||angka==KeyEvent.VK_BACK_SPACE||angka==KeyEvent.VK_DELETE)){
           
           getToolkit().beep();
           evt.consume();
            
             JOptionPane.showMessageDialog(this, "Inputan Harus Berbentuk Angka", "Informasi", JOptionPane.WARNING_MESSAGE);
       }
       
        
        
        if (tfProductId.getText().length() == 13){
             evt.consume();
            JOptionPane.showMessageDialog(this, "Product Id Melebihi 13 karakter", "Informasi", JOptionPane.WARNING_MESSAGE);
             
         }
    }//GEN-LAST:event_tfProductIdKeyTyped

    private void tfInvoiceNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfInvoiceNumberKeyTyped

       char angka = evt.getKeyChar();
       
       if (!(Character.isDigit(angka)||angka==KeyEvent.VK_BACK_SPACE||angka==KeyEvent.VK_DELETE)){
           
           getToolkit().beep();
           evt.consume();
            
             JOptionPane.showMessageDialog(this, "Inputan Harus Berbentuk Angka", "Informasi", JOptionPane.WARNING_MESSAGE);
       }
       
        
        
        
        if (tfInvoiceNumber.getText().length() ==10){
             evt.consume();
            JOptionPane.showMessageDialog(this, "Invoice Number Melebihi 10 karakter", "Informasi", JOptionPane.WARNING_MESSAGE);
       }
         
       
    }//GEN-LAST:event_tfInvoiceNumberKeyTyped

    private void jtCustomerIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtCustomerIdKeyTyped

           char angka = evt.getKeyChar();
       
       if (!(Character.isDigit(angka)||angka==KeyEvent.VK_BACK_SPACE||angka==KeyEvent.VK_DELETE)){
           
           getToolkit().beep();
           evt.consume();
            
             JOptionPane.showMessageDialog(this, "Inputan Harus Berbentuk Angka", "Informasi", JOptionPane.WARNING_MESSAGE);
       }
       

        if (jtCustomerId.getText().length() ==5){
            evt.consume();
            JOptionPane.showMessageDialog(this, "Customer Id Melebihi 5 karakter", "Informasi", JOptionPane.WARNING_MESSAGE);
        }
        
        
    }//GEN-LAST:event_jtCustomerIdKeyTyped

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField12KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField12KeyTyped
        char angka = evt.getKeyChar();
       
       if (!(Character.isDigit(angka)||angka==KeyEvent.VK_BACK_SPACE||angka==KeyEvent.VK_DELETE)){
           
           getToolkit().beep();
           evt.consume();
            
             JOptionPane.showMessageDialog(this, "Inputan Harus Berbentuk Angka", "Informasi", JOptionPane.WARNING_MESSAGE);
       }
       
    }//GEN-LAST:event_jTextField12KeyTyped

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        inputMain.removeAll();
        inputMain.repaint();
        inputMain.revalidate();
        
        
        inputMain.add(PanelInput);
        inputMain.repaint();
        inputMain.revalidate();
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        inputMain.removeAll();
        inputMain.repaint();
        inputMain.revalidate();
        
        
        inputMain.add(jPanel4);
        inputMain.repaint();
        inputMain.revalidate();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void bersihkan() {
        jtUsername.setText("");
        jpPassword.setText("");
        jtNama.setText("");
        jaAlamat.setText("");
        jtNoTelp.setText("");
    }

    public static void summonCashierPanel() {
        CashierPanel cashier = new CashierPanel();
        cashier.setSize(1150, 695);
        cashier.setLocationRelativeTo(null);
        cashier.setVisible(true);
    }

//    private void recolor(){
//        jlProfile.setForeground(Color.BLACK);
//        jlInput.setForeground(Color.BLACK);
//        jlMember.setForeground(Color.BLACK);
//        jlTransaksi.setForeground(Color.BLACK);
//          
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashierPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashierPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashierPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashierPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                summonCashierPanel();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel InputPanel;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JPanel PanelInput;
    private javax.swing.JPanel ProfilePanel;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel imgProduct;
    private javax.swing.JLabel imgTransaction;
    private javax.swing.JLabel imgWelcome;
    private javax.swing.JPanel inputMain;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextArea jaAlamat;
    private javax.swing.JPasswordField jpPassword;
    private javax.swing.JComboBox<String> jsGender;
    private javax.swing.JTextField jtCustomerId;
    private javax.swing.JTextField jtNama;
    private javax.swing.JTextField jtNoTelp;
    private javax.swing.JTextField jtUsername;
    private javax.swing.JLabel label;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel memberRegisterPanel;
    private javax.swing.JTextField tfInvoiceNumber;
    private javax.swing.JTextField tfProductId;
    private javax.swing.JPanel transaksiPanel;
    private javax.swing.JLabel tvAbout;
    private javax.swing.JLabel tvMember;
    private javax.swing.JLabel tvProduct;
    private javax.swing.JLabel tvTransaction;
    private javax.swing.JLabel tvUser;
    private javax.swing.JLabel tvWelcome;
    private javax.swing.JPanel welcomePanel;
    // End of variables declaration//GEN-END:variables
}
