/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.Format;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.Date;

/**
 *
 * @author muham
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfUsername = new javax.swing.JTextField();
        tfPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        tvRegister = new javax.swing.JLabel();
        imgLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        tfUsername.setText("zrfxv");
        tfUsername.setBorder(null);
        getContentPane().add(tfUsername);
        tfUsername.setBounds(440, 390, 320, 50);

        tfPassword.setText("kucing123");
        tfPassword.setBorder(null);
        getContentPane().add(tfPassword);
        tfPassword.setBounds(440, 460, 320, 50);

        btnLogin.setBackground(new java.awt.Color(0, 212, 109));
        btnLogin.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin);
        btnLogin.setBounds(510, 550, 150, 50);

        tvRegister.setForeground(java.awt.Color.gray);
        tvRegister.setText("Lupa Password?");
        tvRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tvRegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tvRegisterMouseExited(evt);
            }
        });
        getContentPane().add(tvRegister);
        tvRegister.setBounds(690, 610, 110, 40);

        imgLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/login.png"))); // NOI18N
        getContentPane().add(imgLogin);
        imgLogin.setBounds(0, -10, 1155, 716);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        try {
            Statement statement = AppDatabase.getConnection().createStatement();

            ResultSet resultSet = statement.executeQuery("select * from employee where "
                    + "username = '" + tfUsername.getText() + "' and "
                    + "password = '" + String.valueOf(tfPassword.getPassword()) + "'");

            resultSet.last();
            if (resultSet.getString("level").equals("admin")) {
                dispose();
                AdminPanel adminPanel = new AdminPanel();
                adminPanel.setLocationRelativeTo(null);
                adminPanel.setVisible(true);
            } else if (resultSet.getString("level").equals("cashier")) {
                dispose();
                CashierPanel.summonCashierPanel();
            }

            Encapsulation.setUsername(resultSet.getString("username"));
            Encapsulation.setName(resultSet.getString("name"));
            System.out.println(Encapsulation.getUsername());

        } catch (SQLException e) {
            System.err.println("Query login gagal");
            JOptionPane.showMessageDialog(this, "Maaf Password atau Username Anda Salah", "Informasi", JOptionPane.INFORMATION_MESSAGE);

        }

    }//GEN-LAST:event_btnLoginActionPerformed

    private void tvRegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tvRegisterMouseEntered
        tvRegister.setForeground(Color.green);
    }//GEN-LAST:event_tvRegisterMouseEntered

    private void tvRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tvRegisterMouseExited
        tvRegister.setForeground(Color.gray);
    }//GEN-LAST:event_tvRegisterMouseExited
    
    public void date (){
       Date data = new Date();
       SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
       String tanggal = sdf.format(data);
      
    }
    
    
    
    
    public static void summonLoginPanel() {
        Login loginPanel = new Login();
        loginPanel.setSize(1155, 716);
        loginPanel.setLocationRelativeTo(null);
        loginPanel.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                summonLoginPanel();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel imgLogin;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfUsername;
    private javax.swing.JLabel tvRegister;
    // End of variables declaration//GEN-END:variables
}
