/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author muham
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfUsername = new javax.swing.JTextField();
        tfPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        tvRegister = new javax.swing.JLabel();
        imgLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        tfUsername.setText("heathcliff");
        tfUsername.setBorder(null);
        getContentPane().add(tfUsername);
        tfUsername.setBounds(450, 180, 280, 40);

        tfPassword.setText("suprax125");
        getContentPane().add(tfPassword);
        tfPassword.setBounds(450, 240, 280, 40);

        btnLogin.setBackground(new java.awt.Color(0, 212, 109));
        btnLogin.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin);
        btnLogin.setBounds(510, 330, 150, 50);

        tvRegister.setForeground(java.awt.Color.gray);
        tvRegister.setText("Lupa Password?");
        tvRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tvRegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tvRegisterMouseExited(evt);
            }
        });
        getContentPane().add(tvRegister);
        tvRegister.setBounds(690, 460, 110, 40);
        getContentPane().add(imgLogin);
        imgLogin.setBounds(0, -2, 0, 0);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        try {
            Statement statement = AppDatabase.getConnection().createStatement();

            ResultSet resultSet = statement.executeQuery("select * from employee where "
                    + "username = '" + tfUsername.getText() + "' and "
                    + "password = '" + String.valueOf(tfPassword.getPassword()) + "'");

            resultSet.last();
            if (resultSet.getString("level").equals("admin")) {
                dispose();
                AdminPanel adminPanel = new AdminPanel();
                adminPanel.setLocationRelativeTo(null);
                adminPanel.setVisible(true);
            } else if (resultSet.getString("level").equals("cashier")) {
                dispose();
                CashierPanel cashierPanel = new CashierPanel();
                cashierPanel.setLocationRelativeTo(null);
                cashierPanel.setVisible(true);
            }
            System.out.println("Level = " + resultSet.getString("level"));

        } catch (SQLException e) {
            System.err.println("Query login gagal");
            JOptionPane.showMessageDialog(this, "Maaf Password atau Username Anda Salah", "Informasi", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void tvRegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tvRegisterMouseEntered
        tvRegister.setForeground(Color.green);
    }//GEN-LAST:event_tvRegisterMouseEntered

    private void tvRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tvRegisterMouseExited
        tvRegister.setForeground(Color.gray);
    }//GEN-LAST:event_tvRegisterMouseExited

    public static void summonLoginPanel() {
        Login loginPanel = new Login();
        loginPanel.setSize(817, 555);
        loginPanel.setLocationRelativeTo(null);
        loginPanel.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                summonLoginPanel();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel imgLogin;
    private javax.swing.JPasswordField tfPassword;
    private javax.swing.JTextField tfUsername;
    private javax.swing.JLabel tvRegister;
    // End of variables declaration//GEN-END:variables
}
